const en = {
  title: 'Family accounts', intro: 'Each active child has a separate login. Family access belongs to the guardian verified against the signed annual agreement.',
  createInvite: 'Create missing accounts and invite', resend: 'Send invitations again', verify: 'Verify guardian', signedContract: 'Signed annual agreement',
  verifyHelp: 'Check the signed agreement itself. Contact details on the child card are only a suggestion. Enter the guardian named in that agreement.',
  confirmGuardian: 'I checked the signed agreement and confirm this guardian and their email.',
  split: 'Separate the child login', confirmSplit: 'I confirm: keep the parent account and create a separate child login. Agreements and lesson history stay with this child.',
  created: 'Created', invited: 'Invited', activated: 'Activated', firstLogin: 'Has logged in', none: 'Not yet', guardian: 'Parent', child: 'Child',
  choosePassword: 'Choose your password', passwordHint: 'At least 10 characters. This invitation sets a password only after you confirm.', passwordMismatch: 'Passwords do not match.',
  batchHint: 'Select up to 5 children at a time.', annualRequired: 'A signed annual agreement is required.', guardianRequired: 'Verify the guardian from the signed agreement.',
  sharedReview: 'The parent and child share a login. Review and separate it first.', conflict: 'Account or guardian details conflict. Review is required.',
  unavailable: 'Family account setup is unavailable.', failed: 'The action could not be completed.', actionDone: 'Selected children processed. Check the account statuses.',
  busy: 'This child is being processed. Try again shortly.', noAccounts: 'Create the missing accounts first.', qaOpen: 'Open invitation', studentEmail: 'Child email', personalCode: 'Guardian personal code',
};
type ActivationIntroCopy = { activationStudentIntro: string; activationParentIntro: string; activationReadyIntro: string; activationSuccess: string };
export type SchoolFamilyAccountCopy = typeof en & ActivationIntroCopy;
const lt: typeof en = {
  title: 'Šeimos paskyros', intro: 'Kiekvienas aktyvus vaikas turi atskirą prisijungimą. Šeimos prieiga suteikiama pagal pasirašytą metinę sutartį patikrintam tėvui.',
  createInvite: 'Sukurti trūkstamas paskyras ir pakviesti', resend: 'Pakartoti kvietimus', verify: 'Patikrinti tėvą', signedContract: 'Pasirašyta metinė sutartis',
  verifyHelp: 'Patikrinkite pačią pasirašytą sutartį. Vaiko kortelės kontaktai yra tik pasiūlymas. Įrašykite šioje sutartyje nurodytą tėvą.',
  confirmGuardian: 'Patikrinau pasirašytą sutartį ir patvirtinu šį tėvą bei jo el. paštą.',
  split: 'Atskirti vaiko prisijungimą', confirmSplit: 'Patvirtinu: palikti tėvo paskyrą ir sukurti atskirą vaiko prisijungimą. Sutartys ir užsiėmimų istorija lieka prie šio vaiko.',
  created: 'Sukurta', invited: 'Pakviesta', activated: 'Aktyvuota', firstLogin: 'Prisijungė', none: 'Dar ne', guardian: 'Tėvas', child: 'Vaikas',
  choosePassword: 'Pasirinkite slaptažodį', passwordHint: 'Bent 10 simbolių. Slaptažodis nustatomas tik jums patvirtinus šį kvietimą.', passwordMismatch: 'Slaptažodžiai nesutampa.',
  batchHint: 'Vienu metu pasirinkite iki 5 vaikų.', annualRequired: 'Reikia pasirašytos metinės sutarties.', guardianRequired: 'Patikrinkite tėvą pagal pasirašytą sutartį.',
  sharedReview: 'Tėvas ir vaikas naudoja bendrą prisijungimą. Pirmiausia jį patikrinkite ir atskirkite.', conflict: 'Paskyros arba tėvo duomenys nesutampa. Reikia patikros.',
  unavailable: 'Šeimos paskyrų paruošimas nepasiekiamas.', failed: 'Nepavyko atlikti veiksmo.', actionDone: 'Pasirinkti vaikai apdoroti. Patikrinkite paskyrų būsenas.',
  busy: 'Šio vaiko duomenys šiuo metu tvarkomi. Netrukus bandykite dar kartą.', noAccounts: 'Pirmiausia sukurkite trūkstamas paskyras.', qaOpen: 'Atidaryti kvietimą', studentEmail: 'Vaiko el. paštas', personalCode: 'Tėvo asmens kodas',
};

const keys = Object.keys(en) as Array<keyof typeof en>;
function translated(values: string): typeof en {
  const entries = values.split('|');
  if (entries.length !== keys.length) throw new Error('Incomplete school family account translation');
  return Object.fromEntries(keys.map((key, index) => [key, entries[index]])) as typeof en;
}

/** These school-specific strings are localized independently to avoid shared dictionary edit collisions. */
const accountTranslations: Record<string, typeof en> = {
  lt, en,
  pl: translated('Konta rodzinne|Każde aktywne dziecko ma osobny login. Dostęp rodzinny otrzymuje opiekun zweryfikowany na podstawie podpisanej umowy rocznej.|Utwórz brakujące konta i zaproś|Wyślij zaproszenia ponownie|Zweryfikuj opiekuna|Podpisana umowa roczna|Sprawdź podpisaną umowę. Dane kontaktowe na karcie dziecka są tylko sugestią. Wpisz opiekuna wskazanego w umowie.|Sprawdzono podpisaną umowę. Potwierdzam tego opiekuna i jego adres e-mail.|Oddziel login dziecka|Potwierdzam: zachowaj konto rodzica i utwórz osobny login dziecka. Umowy i historia zajęć pozostają przypisane do dziecka.|Utworzono|Zaproszono|Aktywowano|Zalogowano się|Jeszcze nie|Rodzic|Dziecko|Wybierz hasło|Co najmniej 10 znaków. Hasło zostanie ustawione dopiero po potwierdzeniu zaproszenia.|Hasła nie są zgodne.|Wybierz maksymalnie 5 dzieci naraz.|Wymagana jest podpisana umowa roczna.|Zweryfikuj opiekuna na podstawie podpisanej umowy.|Rodzic i dziecko używają wspólnego loginu. Najpierw go zweryfikuj i rozdziel.|Dane konta lub opiekuna są sprzeczne. Wymagana jest weryfikacja.|Konfiguracja kont rodzinnych jest niedostępna.|Nie udało się wykonać działania.|Przetworzono wybrane dzieci. Sprawdź stany kont.|Dane dziecka są przetwarzane. Spróbuj za chwilę.|Najpierw utwórz brakujące konta.|Otwórz zaproszenie|E-mail dziecka|Numer identyfikacyjny opiekuna'),
  lv: translated('Ģimenes konti|Katram aktīvajam bērnam ir atsevišķs pieslēgšanās vārds. Ģimenes piekļuvi saņem aizbildnis, kas pārbaudīts pēc parakstītā gada līguma.|Izveidot trūkstošos kontus un uzaicināt|Atkārtoti nosūtīt uzaicinājumus|Pārbaudīt aizbildni|Parakstītais gada līgums|Pārbaudiet parakstīto līgumu. Bērna kartītes kontaktinformācija ir tikai ieteikums. Ievadiet līgumā norādīto aizbildni.|Esmu pārbaudījis parakstīto līgumu un apstiprinu aizbildni un viņa e-pastu.|Atdalīt bērna pieslēgšanos|Apstiprinu: saglabāt vecāka kontu un izveidot atsevišķu bērna pieslēgšanos. Līgumi un nodarbību vēsture paliek pie bērna.|Izveidots|Uzaicināts|Aktivizēts|Ir pieslēdzies|Vēl nav|Vecāks|Bērns|Izvēlieties paroli|Vismaz 10 rakstzīmes. Parole tiek iestatīta tikai pēc uzaicinājuma apstiprināšanas.|Paroles nesakrīt.|Vienlaikus izvēlieties līdz 5 bērniem.|Nepieciešams parakstīts gada līgums.|Pārbaudiet aizbildni pēc parakstītā līguma.|Vecāks un bērns izmanto kopīgu pieslēgšanos. Vispirms to pārbaudiet un atdaliet.|Konta vai aizbildņa dati nesakrīt. Nepieciešama pārbaude.|Ģimenes kontu sagatavošana nav pieejama.|Darbību neizdevās pabeigt.|Izvēlētie bērni apstrādāti. Pārbaudiet kontu statusus.|Bērna dati tiek apstrādāti. Drīz mēģiniet vēlreiz.|Vispirms izveidojiet trūkstošos kontus.|Atvērt uzaicinājumu|Bērna e-pasts|Aizbildņa personas kods'),
  ee: translated('Perekontod|Igal aktiivsel lapsel on eraldi sisselogimine. Pere ligipääs antakse allkirjastatud aastase lepingu põhjal kontrollitud vanemale.|Loo puuduvad kontod ja kutsu|Saada kutsed uuesti|Kontrolli vanemat|Allkirjastatud aastane leping|Kontrolli allkirjastatud lepingut. Lapse kaardi kontaktid on ainult soovitus. Sisesta lepingus nimetatud vanem.|Kontrollisin allkirjastatud lepingut ja kinnitan selle vanema ning tema e-posti.|Eralda lapse sisselogimine|Kinnitan: säilita vanema konto ja loo lapsele eraldi sisselogimine. Lepingud ja tundide ajalugu jäävad lapse juurde.|Loodud|Kutsutud|Aktiveeritud|On sisse loginud|Veel mitte|Vanem|Laps|Vali parool|Vähemalt 10 märki. Parool määratakse alles kutse kinnitamisel.|Paroolid ei ühti.|Vali korraga kuni 5 last.|Vajalik on allkirjastatud aastane leping.|Kontrolli vanemat allkirjastatud lepingu põhjal.|Vanem ja laps jagavad sisselogimist. Kontrolli ja eralda see kõigepealt.|Konto või vanema andmed ei ühti. Vajalik on kontroll.|Perekontode seadistamine pole saadaval.|Toimingut ei saanud lõpetada.|Valitud lapsed on töödeldud. Kontrolli kontode olekut.|Lapse andmeid töödeldakse. Proovi varsti uuesti.|Loo kõigepealt puuduvad kontod.|Ava kutse|Lapse e-post|Vanema isikukood'),
  fr: translated('Comptes familiaux|Chaque enfant actif dispose de son propre accès. Le parent est vérifié à partir du contrat annuel signé avant de recevoir un accès familial.|Créer les comptes manquants et inviter|Renvoyer les invitations|Vérifier le parent|Contrat annuel signé|Vérifiez le contrat signé. Les coordonnées de la fiche enfant ne sont qu’une suggestion. Saisissez le parent indiqué dans ce contrat.|J’ai vérifié le contrat signé et je confirme ce parent ainsi que son adresse e-mail.|Séparer l’accès de l’enfant|Je confirme : conserver le compte du parent et créer un accès distinct pour l’enfant. Les contrats et l’historique des cours restent associés à cet enfant.|Créé|Invité|Activé|Connexion effectuée|Pas encore|Parent|Enfant|Choisissez votre mot de passe|Au moins 10 caractères. Le mot de passe est défini uniquement après confirmation de l’invitation.|Les mots de passe ne correspondent pas.|Sélectionnez jusqu’à 5 enfants à la fois.|Un contrat annuel signé est requis.|Vérifiez le parent dans le contrat signé.|Le parent et l’enfant partagent un accès. Vérifiez-le et séparez-le d’abord.|Les données du compte ou du parent sont incohérentes. Une vérification est requise.|La configuration des comptes familiaux est indisponible.|L’action n’a pas pu être terminée.|Les enfants sélectionnés ont été traités. Vérifiez l’état des comptes.|Cet enfant est en cours de traitement. Réessayez bientôt.|Créez d’abord les comptes manquants.|Ouvrir l’invitation|E-mail de l’enfant|Identifiant personnel du parent'),
  es: translated('Cuentas familiares|Cada menor activo tiene su propio acceso. El acceso familiar se concede al tutor verificado mediante el contrato anual firmado.|Crear cuentas pendientes e invitar|Volver a enviar invitaciones|Verificar tutor|Contrato anual firmado|Comprueba el contrato firmado. Los contactos de la ficha del menor son solo una sugerencia. Introduce el tutor indicado en ese contrato.|He revisado el contrato firmado y confirmo este tutor y su correo.|Separar el acceso del menor|Confirmo: conservar la cuenta del progenitor y crear un acceso propio para el menor. Los contratos y el historial de clases permanecen asociados al menor.|Creada|Invitada|Activada|Ha iniciado sesión|Todavía no|Progenitor|Menor|Elige tu contraseña|Al menos 10 caracteres. La contraseña se establece solo al confirmar esta invitación.|Las contraseñas no coinciden.|Selecciona hasta 5 menores cada vez.|Se requiere un contrato anual firmado.|Verifica al tutor según el contrato firmado.|El progenitor y el menor comparten acceso. Revísalo y sepáralo primero.|Los datos de la cuenta o del tutor no coinciden. Se requiere revisión.|La configuración de cuentas familiares no está disponible.|No se ha podido completar la acción.|Se han procesado los menores seleccionados. Revisa los estados de las cuentas.|Se está procesando este menor. Inténtalo de nuevo en breve.|Crea primero las cuentas pendientes.|Abrir invitación|Correo del menor|Identificación personal del tutor'),
  de: translated('Familienkonten|Jedes aktive Kind erhält einen eigenen Zugang. Familienzugriff erhält der anhand des unterschriebenen Jahresvertrags bestätigte Elternteil.|Fehlende Konten erstellen und einladen|Einladungen erneut senden|Elternteil prüfen|Unterschriebener Jahresvertrag|Prüfen Sie den unterschriebenen Vertrag. Kontaktdaten der Kinderkarte sind nur ein Vorschlag. Tragen Sie den dort genannten Elternteil ein.|Ich habe den unterschriebenen Vertrag geprüft und bestätige diesen Elternteil und seine E-Mail.|Zugang des Kindes trennen|Ich bestätige: Elternkonto behalten und einen getrennten Zugang für das Kind erstellen. Verträge und Unterrichtsverlauf bleiben beim Kind.|Erstellt|Eingeladen|Aktiviert|Angemeldet|Noch nicht|Elternteil|Kind|Passwort wählen|Mindestens 10 Zeichen. Das Passwort wird erst nach Bestätigung dieser Einladung festgelegt.|Die Passwörter stimmen nicht überein.|Wählen Sie bis zu 5 Kinder gleichzeitig.|Ein unterschriebener Jahresvertrag ist erforderlich.|Prüfen Sie den Elternteil anhand des unterschriebenen Vertrags.|Elternteil und Kind teilen einen Zugang. Prüfen und trennen Sie ihn zuerst.|Konto- oder Elterndaten widersprechen sich. Eine Prüfung ist nötig.|Die Einrichtung der Familienkonten ist nicht verfügbar.|Die Aktion konnte nicht abgeschlossen werden.|Ausgewählte Kinder wurden bearbeitet. Prüfen Sie den Kontostatus.|Dieses Kind wird gerade bearbeitet. Versuchen Sie es gleich erneut.|Erstellen Sie zunächst die fehlenden Konten.|Einladung öffnen|E-Mail des Kindes|Persönliche Kennnummer des Elternteils'),
  se: translated('Familjekonton|Varje aktivt barn har en egen inloggning. Familjeåtkomst ges till vårdnadshavaren som verifierats mot det undertecknade årsavtalet.|Skapa saknade konton och bjud in|Skicka inbjudningar igen|Verifiera vårdnadshavare|Undertecknat årsavtal|Kontrollera det undertecknade avtalet. Kontaktuppgifterna på barnets kort är bara ett förslag. Ange vårdnadshavaren i avtalet.|Jag har kontrollerat det undertecknade avtalet och bekräftar vårdnadshavaren och e-postadressen.|Separera barnets inloggning|Jag bekräftar: behåll föräldrakontot och skapa en egen inloggning för barnet. Avtal och lektionshistorik finns kvar för barnet.|Skapat|Inbjudet|Aktiverat|Har loggat in|Inte ännu|Förälder|Barn|Välj lösenord|Minst 10 tecken. Lösenordet anges först när du bekräftar inbjudan.|Lösenorden matchar inte.|Välj högst 5 barn åt gången.|Ett undertecknat årsavtal krävs.|Verifiera vårdnadshavaren mot det undertecknade avtalet.|Förälder och barn delar inloggning. Granska och separera den först.|Konto- eller vårdnadshavaruppgifter skiljer sig. Granskning krävs.|Inställning av familjekonton är inte tillgänglig.|Åtgärden kunde inte slutföras.|Valda barn har behandlats. Kontrollera kontostatus.|Barnet behandlas just nu. Försök igen snart.|Skapa de saknade kontona först.|Öppna inbjudan|Barnets e-post|Vårdnadshavarens personnummer'),
  dk: translated('Familiekonti|Hvert aktivt barn har sit eget login. Familieadgang gives til den værge, der er bekræftet ud fra den underskrevne årsaftale.|Opret manglende konti og inviter|Send invitationer igen|Bekræft værge|Underskrevet årsaftale|Kontrollér den underskrevne aftale. Kontaktoplysningerne på barnets kort er kun et forslag. Angiv værgen fra aftalen.|Jeg har kontrolleret den underskrevne aftale og bekræfter værgen og e-mailadressen.|Adskil barnets login|Jeg bekræfter: behold forældrekontoen og opret et særskilt login til barnet. Aftaler og undervisningshistorik bliver ved barnet.|Oprettet|Inviteret|Aktiveret|Har logget ind|Ikke endnu|Forælder|Barn|Vælg adgangskode|Mindst 10 tegn. Adgangskoden fastsættes først, når invitationen bekræftes.|Adgangskoderne er ikke ens.|Vælg op til 5 børn ad gangen.|En underskrevet årsaftale er påkrævet.|Bekræft værgen ud fra den underskrevne aftale.|Forælder og barn deler login. Gennemgå og adskil det først.|Konto- eller værgeoplysninger er modstridende. Kontrol er påkrævet.|Opsætning af familiekonti er ikke tilgængelig.|Handlingen kunne ikke fuldføres.|De valgte børn er behandlet. Kontrollér kontostatus.|Barnet behandles i øjeblikket. Prøv igen om lidt.|Opret først de manglende konti.|Åbn invitation|Barnets e-mail|Værgens personnummer'),
  fi: translated('Perhetilit|Jokaisella aktiivisella lapsella on oma kirjautuminen. Perheen käyttöoikeus myönnetään allekirjoitetusta vuosisopimuksesta vahvistetulle huoltajalle.|Luo puuttuvat tilit ja kutsu|Lähetä kutsut uudelleen|Vahvista huoltaja|Allekirjoitettu vuosisopimus|Tarkista allekirjoitettu sopimus. Lapsen kortin yhteystiedot ovat vain ehdotus. Kirjoita sopimuksessa mainittu huoltaja.|Olen tarkistanut allekirjoitetun sopimuksen ja vahvistan huoltajan sekä hänen sähköpostinsa.|Erota lapsen kirjautuminen|Vahvistan: säilytä vanhemman tili ja luo lapselle erillinen kirjautuminen. Sopimukset ja tuntihistoria säilyvät lapsella.|Luotu|Kutsuttu|Aktivoitu|Kirjautunut|Ei vielä|Vanhempi|Lapsi|Valitse salasana|Vähintään 10 merkkiä. Salasana asetetaan vasta kutsun vahvistamisen jälkeen.|Salasanat eivät täsmää.|Valitse enintään 5 lasta kerrallaan.|Allekirjoitettu vuosisopimus tarvitaan.|Vahvista huoltaja allekirjoitetusta sopimuksesta.|Vanhempi ja lapsi jakavat kirjautumisen. Tarkista ja erota se ensin.|Tilin tai huoltajan tiedot ovat ristiriitaisia. Tarkistus tarvitaan.|Perhetilien määritys ei ole käytettävissä.|Toimintoa ei voitu suorittaa.|Valitut lapset käsitelty. Tarkista tilien tilat.|Lapsen tietoja käsitellään. Yritä pian uudelleen.|Luo ensin puuttuvat tilit.|Avaa kutsu|Lapsen sähköposti|Huoltajan henkilötunnus'),
  no: translated('Familiekontoer|Hvert aktivt barn har egen innlogging. Familietilgang gis til foresatte som er bekreftet mot den signerte årsavtalen.|Opprett manglende kontoer og inviter|Send invitasjoner på nytt|Bekreft foresatt|Signert årsavtale|Kontroller den signerte avtalen. Kontaktopplysningene på barnets kort er bare et forslag. Oppgi foresatte i avtalen.|Jeg har kontrollert den signerte avtalen og bekrefter foresatte og e-postadressen.|Skill ut barnets innlogging|Jeg bekrefter: behold foreldrekontoen og opprett egen innlogging for barnet. Avtaler og undervisningshistorikk blir hos barnet.|Opprettet|Invitert|Aktivert|Har logget inn|Ikke ennå|Forelder|Barn|Velg passord|Minst 10 tegn. Passordet angis først når du bekrefter invitasjonen.|Passordene er ikke like.|Velg opptil 5 barn om gangen.|En signert årsavtale kreves.|Bekreft foresatte fra den signerte avtalen.|Forelder og barn deler innlogging. Kontroller og skill den først.|Konto- eller foresattopplysninger er motstridende. Kontroll kreves.|Oppsett av familiekontoer er utilgjengelig.|Handlingen kunne ikke fullføres.|Valgte barn er behandlet. Kontroller kontostatus.|Barnet behandles nå. Prøv igjen om litt.|Opprett de manglende kontoene først.|Åpne invitasjon|Barnets e-post|Foresattes fødselsnummer'),
  nl: translated('Gezinsaccounts|Elk actief kind heeft een eigen login. Gezinstoegang wordt verleend aan de ouder die op basis van de ondertekende jaarovereenkomst is geverifieerd.|Ontbrekende accounts maken en uitnodigen|Uitnodigingen opnieuw versturen|Ouder verifiëren|Ondertekende jaarovereenkomst|Controleer de ondertekende overeenkomst. Contactgegevens op de kindkaart zijn alleen een suggestie. Vul de ouder uit de overeenkomst in.|Ik heb de ondertekende overeenkomst gecontroleerd en bevestig deze ouder en diens e-mail.|Login van het kind scheiden|Ik bevestig: behoud het ouderaccount en maak een eigen login voor het kind. Overeenkomsten en lesgeschiedenis blijven bij dit kind.|Aangemaakt|Uitgenodigd|Geactiveerd|Heeft ingelogd|Nog niet|Ouder|Kind|Kies je wachtwoord|Minstens 10 tekens. Het wachtwoord wordt pas ingesteld na bevestiging van deze uitnodiging.|De wachtwoorden komen niet overeen.|Selecteer maximaal 5 kinderen tegelijk.|Een ondertekende jaarovereenkomst is vereist.|Verifieer de ouder aan de hand van de ondertekende overeenkomst.|Ouder en kind delen een login. Controleer en scheid deze eerst.|Account- of oudergegevens komen niet overeen. Controle is vereist.|Het instellen van gezinsaccounts is niet beschikbaar.|De actie kon niet worden voltooid.|Geselecteerde kinderen zijn verwerkt. Controleer de accountstatussen.|Dit kind wordt verwerkt. Probeer het binnenkort opnieuw.|Maak eerst de ontbrekende accounts.|Uitnodiging openen|E-mail van het kind|Persoonsnummer van de ouder'),
};
const activationIntroTranslations: Record<string, ActivationIntroCopy> = {
  en: { activationStudentIntro: 'Your student account at {org} is ready. Choose a password below and confirm activation.',
    activationParentIntro: 'Your family account at {org} is ready. Choose a password below and confirm activation.',
    activationReadyIntro: 'This account is already active. Sign in with your password. This invitation does not change it.',
    activationSuccess: 'Your account is active. Sign in with your password.' },
  lt: { activationStudentIntro: 'Mokinio paskyra organizacijoje „{org}“ paruošta. Žemiau pasirinkite slaptažodį ir patvirtinkite aktyvavimą.',
    activationParentIntro: 'Šeimos paskyra organizacijoje „{org}“ paruošta. Žemiau pasirinkite slaptažodį ir patvirtinkite aktyvavimą.',
    activationReadyIntro: 'Paskyra jau aktyvuota. Prisijunkite naudodami savo slaptažodį. Šis kvietimas jo nekeičia.',
    activationSuccess: 'Jūsų paskyra aktyvuota. Prisijunkite naudodami savo slaptažodį.' },
  pl: { activationStudentIntro: 'Twoje konto ucznia w {org} jest gotowe. Wybierz hasło poniżej i potwierdź aktywację.',
    activationParentIntro: 'Twoje konto rodzinne w {org} jest gotowe. Wybierz hasło poniżej i potwierdź aktywację.',
    activationReadyIntro: 'To konto jest już aktywne. Zaloguj się swoim hasłem. To zaproszenie go nie zmienia.',
    activationSuccess: 'Twoje konto jest aktywne. Zaloguj się swoim hasłem.' },
  lv: { activationStudentIntro: 'Jūsu skolēna konts organizācijā {org} ir gatavs. Zemāk izvēlieties paroli un apstipriniet aktivizēšanu.',
    activationParentIntro: 'Jūsu ģimenes konts organizācijā {org} ir gatavs. Zemāk izvēlieties paroli un apstipriniet aktivizēšanu.',
    activationReadyIntro: 'Šis konts jau ir aktīvs. Pieslēdzieties ar savu paroli. Šis uzaicinājums to nemaina.',
    activationSuccess: 'Jūsu konts ir aktīvs. Pieslēdzieties ar savu paroli.' },
  ee: { activationStudentIntro: 'Sinu õpilaskonto organisatsioonis {org} on valmis. Vali allpool parool ja kinnita aktiveerimine.',
    activationParentIntro: 'Sinu perekonto organisatsioonis {org} on valmis. Vali allpool parool ja kinnita aktiveerimine.',
    activationReadyIntro: 'See konto on juba aktiivne. Logi sisse oma parooliga. See kutse ei muuda seda.',
    activationSuccess: 'Sinu konto on aktiivne. Logi sisse oma parooliga.' },
  fr: { activationStudentIntro: 'Votre compte élève chez {org} est prêt. Choisissez un mot de passe ci-dessous et confirmez l’activation.',
    activationParentIntro: 'Votre compte familial chez {org} est prêt. Choisissez un mot de passe ci-dessous et confirmez l’activation.',
    activationReadyIntro: 'Ce compte est déjà actif. Connectez-vous avec votre mot de passe. Cette invitation ne le modifie pas.',
    activationSuccess: 'Votre compte est actif. Connectez-vous avec votre mot de passe.' },
  es: { activationStudentIntro: 'Tu cuenta de estudiante en {org} está preparada. Elige una contraseña abajo y confirma la activación.',
    activationParentIntro: 'Tu cuenta familiar en {org} está preparada. Elige una contraseña abajo y confirma la activación.',
    activationReadyIntro: 'Esta cuenta ya está activa. Inicia sesión con tu contraseña. Esta invitación no la cambia.',
    activationSuccess: 'Tu cuenta está activa. Inicia sesión con tu contraseña.' },
  de: { activationStudentIntro: 'Dein Schülerkonto bei {org} ist bereit. Wähle unten ein Passwort und bestätige die Aktivierung.',
    activationParentIntro: 'Dein Familienkonto bei {org} ist bereit. Wähle unten ein Passwort und bestätige die Aktivierung.',
    activationReadyIntro: 'Dieses Konto ist bereits aktiv. Melde dich mit deinem Passwort an. Diese Einladung ändert es nicht.',
    activationSuccess: 'Dein Konto ist aktiv. Melde dich mit deinem Passwort an.' },
  se: { activationStudentIntro: 'Ditt elevkonto hos {org} är klart. Välj ett lösenord nedan och bekräfta aktiveringen.',
    activationParentIntro: 'Ditt familjekonto hos {org} är klart. Välj ett lösenord nedan och bekräfta aktiveringen.',
    activationReadyIntro: 'Det här kontot är redan aktivt. Logga in med ditt lösenord. Den här inbjudan ändrar det inte.',
    activationSuccess: 'Ditt konto är aktivt. Logga in med ditt lösenord.' },
  dk: { activationStudentIntro: 'Din elevkonto hos {org} er klar. Vælg en adgangskode nedenfor og bekræft aktiveringen.',
    activationParentIntro: 'Din familiekonto hos {org} er klar. Vælg en adgangskode nedenfor og bekræft aktiveringen.',
    activationReadyIntro: 'Denne konto er allerede aktiv. Log ind med din adgangskode. Denne invitation ændrer den ikke.',
    activationSuccess: 'Din konto er aktiv. Log ind med din adgangskode.' },
  fi: { activationStudentIntro: 'Oppilastilisi organisaatiossa {org} on valmis. Valitse salasana alta ja vahvista aktivointi.',
    activationParentIntro: 'Perhetilisi organisaatiossa {org} on valmis. Valitse salasana alta ja vahvista aktivointi.',
    activationReadyIntro: 'Tämä tili on jo aktiivinen. Kirjaudu salasanallasi. Tämä kutsu ei muuta sitä.',
    activationSuccess: 'Tilisi on aktiivinen. Kirjaudu salasanallasi.' },
  no: { activationStudentIntro: 'Elevkontoen din hos {org} er klar. Velg et passord nedenfor og bekreft aktiveringen.',
    activationParentIntro: 'Familiekontoen din hos {org} er klar. Velg et passord nedenfor og bekreft aktiveringen.',
    activationReadyIntro: 'Denne kontoen er allerede aktiv. Logg inn med passordet ditt. Denne invitasjonen endrer det ikke.',
    activationSuccess: 'Kontoen din er aktiv. Logg inn med passordet ditt.' },
  nl: { activationStudentIntro: 'Je leerlingenaccount bij {org} is klaar. Kies hieronder een wachtwoord en bevestig de activering.',
    activationParentIntro: 'Je gezinsaccount bij {org} is klaar. Kies hieronder een wachtwoord en bevestig de activering.',
    activationReadyIntro: 'Dit account is al actief. Log in met je wachtwoord. Deze uitnodiging verandert het niet.',
    activationSuccess: 'Je account is actief. Log in met je wachtwoord.' },
};
export const schoolFamilyAccountTranslations: Record<string, SchoolFamilyAccountCopy> = Object.fromEntries(
  Object.entries(accountTranslations).map(([locale, copy]) => [locale, { ...copy, ...activationIntroTranslations[locale] }]),
);
export function schoolFamilyAccountCopy(locale: string): SchoolFamilyAccountCopy {
  return schoolFamilyAccountTranslations[locale] || schoolFamilyAccountTranslations.en;
}

export function schoolFamilyAccountError(code: string, copy: SchoolFamilyAccountCopy): string {
  if (code === 'annual_contract_required') return copy.annualRequired;
  if (/shared_identity/.test(code)) return copy.sharedReview;
  if (/guardian.*(conflict|invalid)|email_already_registered|related_account_conflict|contact_conflict/.test(code)) return copy.conflict;
  if (/guardian|verification/.test(code)) return copy.guardianRequired;
  if (/setup_required|unavailable|org_not_supported/.test(code)) return copy.unavailable;
  if (code === 'workflow_busy') return copy.busy;
  if (code === 'accounts_not_created') return copy.noAccounts;
  return copy.failed;
}
