import type { Locale } from '../../src/lib/i18n/locales.js';

/** Server-only notification copy. Draft languages still require native review.
 * Common greetings, contacts and status labels use the main dictionaries.
 * Only assignmentBody contains markup; interpolate escaped student names. */
export interface TutorNotificationCopy {
  assignmentSubject: string;
  assignmentBody: string;
  assignmentNoContact: string;
  statusSubject: string;
  statusMore: string;
  statusDaily: string;
}

export const TUTOR_NOTIFICATION_COPY: Record<Locale, TutorNotificationCopy> = {
  'lt': {
    assignmentSubject: "Naujas mokinys priskirtas jums",
    assignmentBody: "Jums buvo priskirtas naujas mokinys: <strong>{student}</strong>.",
    assignmentNoContact: "Dėl pamokų ir bendravimo su mokiniu naudokitės Tutlio platforma (pvz., mokinių puslapis ar žinutės).",
    statusSubject: "Pažymėkite pamokų statusus ({count})",
    statusMore: "… kitų pamokų skaičius: {count}.",
    statusDaily: "Priminimai bus siunčiami kasdien, kol pažymėsite visų pamokų statusus.",
  },
  'en': {
    assignmentSubject: "New student assigned to you",
    assignmentBody: "A new student has been assigned to you: <strong>{student}</strong>.",
    assignmentNoContact: "For lessons and communicating with the student, use Tutlio (e.g. Students page or messages).",
    statusSubject: "Confirm your lesson statuses ({count})",
    statusMore: "… additional lessons: {count}.",
    statusDaily: "Reminders repeat daily until every lesson status is confirmed.",
  },
  'pl': {
    assignmentSubject: "Przypisano Ci nowego ucznia",
    assignmentBody: "Przypisano Ci nowego ucznia: <strong>{student}</strong>.",
    assignmentNoContact: "Korzystaj z Tutlio do prowadzenia lekcji i kontaktu z uczniem, np. z sekcji Uczniowie lub Wiadomości.",
    statusSubject: "Potwierdź statusy lekcji ({count})",
    statusMore: "… liczba pozostałych lekcji: {count}.",
    statusDaily: "Przypomnienia będą wysyłane codziennie, dopóki nie potwierdzisz statusu wszystkich lekcji.",
  },
  'lv': {
    assignmentSubject: "Jums ir piešķirts jauns skolēns",
    assignmentBody: "Jums ir piešķirts jauns skolēns: <strong>{student}</strong>.",
    assignmentNoContact: "Nodarbībām un saziņai ar skolēnu izmantojiet Tutlio, piemēram, sadaļu Skolēni vai Ziņojumi.",
    statusSubject: "Apstipriniet nodarbību statusus ({count})",
    statusMore: "… pārējo nodarbību skaits: {count}.",
    statusDaily: "Atgādinājumi tiks sūtīti katru dienu, līdz apstiprināsiet visu nodarbību statusus.",
  },
  'ee': {
    assignmentSubject: "Teile on määratud uus õpilane",
    assignmentBody: "Teile on määratud uus õpilane: <strong>{student}</strong>.",
    assignmentNoContact: "Kasutage tundide ja õpilasega suhtlemise jaoks Tutliot, näiteks õpilaste või sõnumite lehte.",
    statusSubject: "Kinnitage tundide staatused ({count})",
    statusMore: "… ülejäänud tundide arv: {count}.",
    statusDaily: "Meeldetuletusi saadetakse iga päev, kuni kõigi tundide staatus on kinnitatud.",
  },
  'fr': {
    assignmentSubject: "Un nouvel élève vous a été attribué",
    assignmentBody: "Un nouvel élève vous a été attribué : <strong>{student}</strong>.",
    assignmentNoContact: "Utilisez Tutlio pour les cours et les échanges avec l’élève, par exemple les rubriques Élèves ou Messages.",
    statusSubject: "Confirmez les statuts de vos cours ({count})",
    statusMore: "… nombre de cours supplémentaires : {count}.",
    statusDaily: "Les rappels sont envoyés chaque jour jusqu’à ce que le statut de tous les cours soit confirmé.",
  },
  'es': {
    assignmentSubject: "Se te ha asignado un nuevo estudiante",
    assignmentBody: "Se te ha asignado un nuevo estudiante: <strong>{student}</strong>.",
    assignmentNoContact: "Utiliza Tutlio para las clases y para comunicarte con el estudiante, por ejemplo, las secciones Estudiantes o Mensajes.",
    statusSubject: "Confirma los estados de tus clases ({count})",
    statusMore: "… clases adicionales: {count}.",
    statusDaily: "Recibirás recordatorios diarios hasta que confirmes el estado de todas las clases.",
  },
  'de': {
    assignmentSubject: "Dir wurde ein neuer Schüler zugewiesen",
    assignmentBody: "Dir wurde ein neuer Schüler zugewiesen: <strong>{student}</strong>.",
    assignmentNoContact: "Nutze Tutlio für den Unterricht und den Kontakt mit dem Schüler, zum Beispiel die Bereiche Schüler oder Nachrichten.",
    statusSubject: "Bestätige den Status deiner Unterrichtsstunden ({count})",
    statusMore: "… weitere Unterrichtsstunden: {count}.",
    statusDaily: "Du erhältst täglich Erinnerungen, bis der Status aller Unterrichtsstunden bestätigt ist.",
  },
  'se': {
    assignmentSubject: "En ny elev har tilldelats dig",
    assignmentBody: "En ny elev har tilldelats dig: <strong>{student}</strong>.",
    assignmentNoContact: "Använd Tutlio för lektioner och kontakt med eleven, till exempel sidorna Elever eller Meddelanden.",
    statusSubject: "Bekräfta lektionsstatusarna ({count})",
    statusMore: "… ytterligare lektioner: {count}.",
    statusDaily: "Påminnelser skickas dagligen tills du har bekräftat statusen för alla lektioner.",
  },
  'dk': {
    assignmentSubject: "Du har fået tildelt en ny elev",
    assignmentBody: "Du har fået tildelt en ny elev: <strong>{student}</strong>.",
    assignmentNoContact: "Brug Tutlio til undervisning og kontakt med eleven, for eksempel siderne Elever eller Beskeder.",
    statusSubject: "Bekræft lektionernes status ({count})",
    statusMore: "… yderligere lektioner: {count}.",
    statusDaily: "Du får en påmindelse hver dag, indtil alle lektioners status er bekræftet.",
  },
  'fi': {
    assignmentSubject: "Sinulle on osoitettu uusi oppilas",
    assignmentBody: "Sinulle on osoitettu uusi oppilas: <strong>{student}</strong>.",
    assignmentNoContact: "Käytä Tutliota oppitunteihin ja yhteydenpitoon oppilaan kanssa, esimerkiksi Oppilaat- tai Viestit-sivua.",
    statusSubject: "Vahvista oppituntien tilat ({count})",
    statusMore: "… muita oppitunteja: {count}.",
    statusDaily: "Muistutuksia lähetetään päivittäin, kunnes kaikkien oppituntien tilat on vahvistettu.",
  },
  'no': {
    assignmentSubject: "Du har fått tildelt en ny elev",
    assignmentBody: "Du har fått tildelt en ny elev: <strong>{student}</strong>.",
    assignmentNoContact: "Bruk Tutlio til undervisning og kontakt med eleven, for eksempel sidene Elever eller Meldinger.",
    statusSubject: "Bekreft status for timene ({count})",
    statusMore: "… flere timer: {count}.",
    statusDaily: "Påminnelser sendes daglig til status for alle timene er bekreftet.",
  },
  'nl': {
    assignmentSubject: "Nieuwe leerling aan je toegewezen",
    assignmentBody: "Er is een nieuwe leerling aan je toegewezen: <strong>{student}</strong>.",
    assignmentNoContact: "Gebruik Tutlio voor je lessen en het contact met de leerling, bijvoorbeeld via Leerlingen of Berichten.",
    statusSubject: "Bevestig je lesstatussen ({count})",
    statusMore: "… aantal overige lessen: {count}.",
    statusDaily: "Je ontvangt dagelijks een herinnering totdat je alle lesstatussen hebt bevestigd.",
  },
  'it': {
    assignmentSubject: "Ti è stato assegnato un nuovo studente",
    assignmentBody: "Ti è stato assegnato un nuovo studente: <strong>{student}</strong>.",
    assignmentNoContact: "Usa Tutlio per le lezioni e per comunicare con lo studente, ad esempio le sezioni Studenti o Messaggi.",
    statusSubject: "Conferma gli stati delle lezioni ({count})",
    statusMore: "… altre lezioni: {count}.",
    statusDaily: "Riceverai promemoria ogni giorno finché non avrai confermato lo stato di tutte le lezioni.",
  },
  'pt': {
    assignmentSubject: "Foi-lhe atribuído um novo aluno",
    assignmentBody: "Foi-lhe atribuído um novo aluno: <strong>{student}</strong>.",
    assignmentNoContact: "Utilize o Tutlio para as aulas e para comunicar com o aluno, por exemplo, as secções Alunos ou Mensagens.",
    statusSubject: "Confirme os estados das aulas ({count})",
    statusMore: "… aulas adicionais: {count}.",
    statusDaily: "Receberá lembretes diários até confirmar o estado de todas as aulas.",
  },
  'ro': {
    assignmentSubject: "Ți-a fost repartizat un elev nou",
    assignmentBody: "Ți-a fost repartizat un elev nou: <strong>{student}</strong>.",
    assignmentNoContact: "Folosește Tutlio pentru lecții și comunicarea cu elevul, de exemplu secțiunile Elevi sau Mesaje.",
    statusSubject: "Confirmă stările lecțiilor ({count})",
    statusMore: "… alte lecții: {count}.",
    statusDaily: "Vei primi notificări zilnice până când confirmi starea tuturor lecțiilor.",
  },
  'cs': {
    assignmentSubject: "Byl vám přiřazen nový student",
    assignmentBody: "Byl vám přiřazen nový student: <strong>{student}</strong>.",
    assignmentNoContact: "Pro lekce a komunikaci se studentem používejte Tutlio, například sekci Studenti nebo Zprávy.",
    statusSubject: "Potvrďte stavy lekcí ({count})",
    statusMore: "… další lekce: {count}.",
    statusDaily: "Připomínky se budou posílat každý den, dokud nepotvrdíte stav všech lekcí.",
  },
  'el': {
    assignmentSubject: "Σας ανατέθηκε ένας νέος μαθητής",
    assignmentBody: "Σας ανατέθηκε ένας νέος μαθητής: <strong>{student}</strong>.",
    assignmentNoContact: "Χρησιμοποιήστε το Tutlio για τα μαθήματα και την επικοινωνία με τον μαθητή, για παράδειγμα τις ενότητες Μαθητές ή Μηνύματα.",
    statusSubject: "Επιβεβαιώστε την κατάσταση των μαθημάτων ({count})",
    statusMore: "… επιπλέον μαθήματα: {count}.",
    statusDaily: "Θα λαμβάνετε καθημερινές υπενθυμίσεις μέχρι να επιβεβαιώσετε την κατάσταση όλων των μαθημάτων.",
  },
  'hu': {
    assignmentSubject: "Új tanulót rendeltek Önhöz",
    assignmentBody: "Új tanulót rendeltek Önhöz: <strong>{student}</strong>.",
    assignmentNoContact: "Az órákhoz és a tanulóval való kapcsolattartáshoz használja a Tutliót, például a Tanulók vagy az Üzenetek oldalt.",
    statusSubject: "Erősítse meg az órák állapotát ({count})",
    statusMore: "… további órák száma: {count}.",
    statusDaily: "Az emlékeztetőket naponta küldjük, amíg minden óra állapotát meg nem erősíti.",
  },
  'bg': {
    assignmentSubject: "Към вас е разпределен нов ученик",
    assignmentBody: "Към вас е разпределен нов ученик: <strong>{student}</strong>.",
    assignmentNoContact: "Използвайте Tutlio за уроците и за връзка с ученика, например разделите Ученици или Съобщения.",
    statusSubject: "Потвърдете статусите на уроците ({count})",
    statusMore: "… допълнителни уроци: {count}.",
    statusDaily: "Ще получавате напомняния всеки ден, докато потвърдите статуса на всички уроци.",
  },
  'hr': {
    assignmentSubject: "Dodijeljen vam je novi učenik",
    assignmentBody: "Dodijeljen vam je novi učenik: <strong>{student}</strong>.",
    assignmentNoContact: "Koristite Tutlio za nastavu i komunikaciju s učenikom, primjerice odjeljke Učenici ili Poruke.",
    statusSubject: "Potvrdite statuse sati ({count})",
    statusMore: "… dodatni sati: {count}.",
    statusDaily: "Podsjetnici se šalju svaki dan dok ne potvrdite status svih sati.",
  },
  'sk': {
    assignmentSubject: "Bol vám priradený nový žiak",
    assignmentBody: "Bol vám priradený nový žiak: <strong>{student}</strong>.",
    assignmentNoContact: "Na hodiny a komunikáciu so žiakom používajte Tutlio, napríklad sekcie Žiaci alebo Správy.",
    statusSubject: "Potvrďte stavy hodín ({count})",
    statusMore: "… ďalšie hodiny: {count}.",
    statusDaily: "Pripomienky sa budú posielať každý deň, kým nepotvrdíte stav všetkých hodín.",
  },
  'sl': {
    assignmentSubject: "Dodeljen vam je bil nov učenec",
    assignmentBody: "Dodeljen vam je bil nov učenec: <strong>{student}</strong>.",
    assignmentNoContact: "Za ure in komunikacijo z učencem uporabljajte Tutlio, na primer razdelka Učenci ali Sporočila.",
    statusSubject: "Potrdite stanja ur ({count})",
    statusMore: "… dodatne ure: {count}.",
    statusDaily: "Opomnike boste prejemali vsak dan, dokler ne potrdite stanja vseh ur.",
  },
  'hi': {
    assignmentSubject: "आपको एक नया विद्यार्थी सौंपा गया है",
    assignmentBody: "आपको एक नया विद्यार्थी सौंपा गया है: <strong>{student}</strong>।",
    assignmentNoContact: "कक्षाओं और विद्यार्थी से बातचीत के लिए Tutlio का इस्तेमाल करें, जैसे विद्यार्थी या संदेश अनुभाग।",
    statusSubject: "अपनी कक्षाओं की स्थिति की पुष्टि करें ({count})",
    statusMore: "… अन्य कक्षाओं की संख्या: {count}।",
    statusDaily: "सभी कक्षाओं की स्थिति की पुष्टि होने तक हर दिन रिमाइंडर भेजे जाएंगे।",
  },
  'ko': {
    assignmentSubject: "새 학생이 배정되었습니다",
    assignmentBody: "새 학생이 배정되었습니다: <strong>{student}</strong>.",
    assignmentNoContact: "수업과 학생과의 소통에는 Tutlio의 학생 또는 메시지 페이지를 이용하세요.",
    statusSubject: "수업 상태를 확인해 주세요 ({count})",
    statusMore: "… 추가 수업: {count}개.",
    statusDaily: "모든 수업 상태를 확인할 때까지 매일 알림이 발송됩니다.",
  },
  'ja': {
    assignmentSubject: "新しい生徒が割り当てられました",
    assignmentBody: "新しい生徒が割り当てられました：<strong>{student}</strong>。",
    assignmentNoContact: "レッスンや生徒との連絡には、Tutlioの生徒ページやメッセージ機能をご利用ください。",
    statusSubject: "レッスンの状況を確認してください（{count}件）",
    statusMore: "… その他のレッスン：{count}件。",
    statusDaily: "すべてのレッスンの状況が確認されるまで、毎日リマインダーを送信します。",
  },
  'id': {
    assignmentSubject: "Siswa baru ditugaskan kepada Anda",
    assignmentBody: "Siswa baru ditugaskan kepada Anda: <strong>{student}</strong>.",
    assignmentNoContact: "Gunakan Tutlio untuk kegiatan les dan komunikasi dengan siswa, misalnya halaman Siswa atau Pesan.",
    statusSubject: "Konfirmasikan status sesi les Anda ({count})",
    statusMore: "… sesi les lainnya: {count}.",
    statusDaily: "Pengingat dikirim setiap hari sampai status semua sesi les dikonfirmasi.",
  },
  'ar': {
    assignmentSubject: "تم تعيين طالب جديد لك",
    assignmentBody: "تم تعيين طالب جديد لك: <strong>{student}</strong>.",
    assignmentNoContact: "استخدم Tutlio للدروس والتواصل مع الطالب، مثل صفحة الطلاب أو الرسائل.",
    statusSubject: "أكّد حالات الدروس ({count})",
    statusMore: "… عدد الدروس الإضافية: {count}.",
    statusDaily: "ستُرسل التذكيرات يوميًا حتى يتم تأكيد حالات جميع الدروس.",
  },
  'pt-br': {
    assignmentSubject: "Um novo aluno foi atribuído a você",
    assignmentBody: "Um novo aluno foi atribuído a você: <strong>{student}</strong>.",
    assignmentNoContact: "Use o Tutlio para as aulas e para conversar com o aluno, por exemplo, as seções Alunos ou Mensagens.",
    statusSubject: "Confirme os status das aulas ({count})",
    statusMore: "… aulas adicionais: {count}.",
    statusDaily: "Você receberá lembretes diários até confirmar o status de todas as aulas.",
  },
  'es-mx': {
    assignmentSubject: "Se te asignó un nuevo estudiante",
    assignmentBody: "Se te asignó un nuevo estudiante: <strong>{student}</strong>.",
    assignmentNoContact: "Usa Tutlio para las clases y para comunicarte con el estudiante, por ejemplo, las secciones Estudiantes o Mensajes.",
    statusSubject: "Confirma los estados de tus clases ({count})",
    statusMore: "… clases adicionales: {count}.",
    statusDaily: "Recibirás recordatorios diarios hasta que confirmes el estado de todas las clases.",
  },
  'fil': {
    assignmentSubject: "May bagong estudyanteng itinalaga sa iyo",
    assignmentBody: "May bagong estudyanteng itinalaga sa iyo: <strong>{student}</strong>.",
    assignmentNoContact: "Gamitin ang Tutlio para sa mga sesyon at pakikipag-ugnayan sa estudyante, halimbawa ang pahina ng Mga Estudyante o Mga Mensahe.",
    statusSubject: "Kumpirmahin ang mga katayuan ng sesyon ({count})",
    statusMore: "… iba pang sesyon: {count}.",
    statusDaily: "Magpapadala ng paalala araw-araw hanggang makumpirma ang katayuan ng lahat ng sesyon.",
  },
  'he': {
    assignmentSubject: "הוקצה לך תלמיד חדש",
    assignmentBody: "הוקצה לך תלמיד חדש: <strong>{student}</strong>.",
    assignmentNoContact: "לשיעורים ולתקשורת עם התלמיד יש להשתמש ב-Tutlio, למשל בעמוד התלמידים או בהודעות.",
    statusSubject: "יש לאשר את מצבי השיעורים ({count})",
    statusMore: "… מספר השיעורים הנוספים: {count}.",
    statusDaily: "תזכורות יישלחו מדי יום עד לאישור מצבם של כל השיעורים.",
  },
  'uk': {
    assignmentSubject: "Вам призначено нового учня",
    assignmentBody: "Вам призначено нового учня: <strong>{student}</strong>.",
    assignmentNoContact: "Використовуйте Tutlio для уроків і спілкування з учнем, наприклад розділи «Учні» або «Повідомлення».",
    statusSubject: "Підтвердьте статуси уроків ({count})",
    statusMore: "… додаткові уроки: {count}.",
    statusDaily: "Нагадування надсилатимуться щодня, доки ви не підтвердите статуси всіх уроків.",
  },
  'zh-hk': {
    assignmentSubject: "已為你安排新學生",
    assignmentBody: "已為你安排新學生：<strong>{student}</strong>。",
    assignmentNoContact: "請使用 Tutlio 安排課堂及與學生聯絡，例如「學生」或「訊息」頁面。",
    statusSubject: "請確認課堂狀態（{count}）",
    statusMore: "… 其他課堂：{count}。",
    statusDaily: "系統會每天發送提醒，直至所有課堂狀態均已確認。",
  },
  'tr': {
    assignmentSubject: "Size yeni bir öğrenci atandı",
    assignmentBody: "Size yeni bir öğrenci atandı: <strong>{student}</strong>.",
    assignmentNoContact: "Dersler ve öğrenciyle iletişim için Tutlio'yu, örneğin Öğrenciler veya Mesajlar sayfasını kullanın.",
    statusSubject: "Ders durumlarını onaylayın ({count})",
    statusMore: "… diğer derslerin sayısı: {count}.",
    statusDaily: "Tüm derslerin durumları onaylanana kadar her gün hatırlatma gönderilir.",
  },
  'th': {
    assignmentSubject: "มีนักเรียนใหม่ที่ได้รับมอบหมายให้คุณ",
    assignmentBody: "มีนักเรียนใหม่ที่ได้รับมอบหมายให้คุณ: <strong>{student}</strong>",
    assignmentNoContact: "ใช้ Tutlio สำหรับการเรียนและการติดต่อกับนักเรียน เช่น หน้านักเรียนหรือข้อความ",
    statusSubject: "ยืนยันสถานะบทเรียน ({count})",
    statusMore: "… บทเรียนเพิ่มเติม: {count}",
    statusDaily: "ระบบจะส่งการแจ้งเตือนทุกวันจนกว่าจะยืนยันสถานะของทุกบทเรียน",
  },
};
