export const schoolPreview = {
  ok: true,
  contractId: 'c3',
  contractNumber: 'PP-LEGAL-WITHIN14',
  studentName: 'QA Legal Per 14 d.',
  schoolName: 'Demo Mokykla',
  schoolEmail: 'demo@example.com',
  pdfUrl: 'https://example.com/sutartis.pdf',
  body: 'NUOTOLINIŲ PAPILDOMŲ PAMOKŲ SUTARTIS\n1. Šalys',
  order: {
    revision_label: 'QA',
    service_name: 'QA Matematika',
    service_type: 'group',
    platform: 'Google Meet',
    duration_minutes: 45,
    schedule_slots: [{ weekday: 2, start_time: '16:00', end_time: '16:45' }],
    schedule_label: 'antradienis 16:00–16:45',
    start_date: '2026-08-30',
    end_date: '2027-06-13',
    unit_price_eur: 18,
    vat_status: 'PVM neapmokestinama',
    base_lessons_per_month: 8,
    indicative_monthly_eur: 144,
    individual_cancel_terms: 'netaikoma',
    school_email: 'demo@example.com',
    school_phone: '',
    data_protection_contact: 'demo@example.com',
  },
  parentEditableFields: [],
  startWithin14Applies: true,
  recordingsEnabled: true,
  startWithin14CheckboxText: 'Prašau pradėti teikti paslaugas nepasibaigus 14 dienų',
  legalLinks: { withdrawalForm: '/legal/extra-lessons-withdrawal-form.html' },
};