const keys = ['title','help','source','sourcePlaceholder','noPaidInvoices','pickInvoice','amount','reason','save','history','empty','used','remaining','void','voidReason','voided','applied','fromMonth','total','due','released'] as const;
const extra = {
  lt: ['Pasirinkite apmokėtą sąskaitą', 'Nėra apmokėtų sąskaitų, iš kurių galima registruoti permoką.', 'Pasirinkite sąskaitą iš sąrašo.'],
  en: ['Select a paid invoice', 'There are no paid invoices available to register an overpayment from.', 'Select an invoice from the list.'],
  pl: ['Wybierz opłaconą fakturę', 'Brak opłaconych faktur, z których można zarejestrować nadpłatę.', 'Wybierz fakturę z listy.'],
  lv: ['Izvēlieties apmaksātu rēķinu', 'Nav apmaksātu rēķinu, no kuriem reģistrēt pārmaksu.', 'Izvēlieties rēķinu no saraksta.'],
  ee: ['Vali makstud arve', 'Üle makstud arveid puuduvad, mille alusel enammakset registreerida.', 'Vali arve loendist.'],
  fr: ['Sélectionnez une facture payée', 'Aucune facture payée disponible pour enregistrer un trop-perçu.', 'Sélectionnez une facture dans la liste.'],
  es: ['Seleccione una factura pagada', 'No hay facturas pagadas disponibles para registrar un pago en exceso.', 'Seleccione una factura de la lista.'],
  de: ['Bezahlte Rechnung auswählen', 'Es gibt keine bezahlten Rechnungen, aus denen eine Überzahlung registriert werden kann.', 'Wählen Sie eine Rechnung aus der Liste.'],
  se: ['Välj en betald faktura', 'Det finns inga betalda fakturor att registrera en överbetalning från.', 'Välj en faktura från listan.'],
  dk: ['Vælg en betalt faktura', 'Der er ingen betalte fakturaer, som overbetaling kan registreres fra.', 'Vælg en faktura fra listen.'],
  fi: ['Valitse maksettu lasku', 'Maksettuja laskuja ei ole, joista liikamaksu voitaisiin rekisteröidä.', 'Valitse lasku luettelosta.'],
  no: ['Velg en betalt faktura', 'Det finnes ingen betalte fakturaer å registrere overbetaling fra.', 'Velg en faktura fra listen.'],
  nl: ['Selecteer een betaalde factuur', 'Er zijn geen betaalde facturen om een overbetaling van te registreren.', 'Selecteer een factuur uit de lijst.'],
} as const;
const copy: Record<string, string[]> = {
  lt: ['Permokos','Permoka automatiškai užskaitoma naujai to paties mokėtojo vaiko sąskaitai už vėlesnį mėnesį. Suma, priežastis ir administratorius išsaugomi istorijoje.','Apmokėta sąskaita', ...extra.lt,'Permoka (€)','Permokos priežastis','Perkelti permoką','Permokų istorija','Permokų nėra.','Panaudota','Likutis','Atšaukti permoką','Atšaukimo priežastis','Atšaukta','Užskaityta permoka','Permoka iš {month}','Sąskaitos suma','Mokėti','Sąskaita atšaukta; suma grąžinta į likutį'],
  en: ['Overpayments','An overpayment is automatically applied to a new invoice for a later month for the same payer’s child. The amount, reason and administrator are recorded.','Paid invoice', ...extra.en,'Overpayment (€)','Overpayment reason','Carry over payment','Overpayment history','No overpayments.','Used','Remaining','Cancel overpayment','Cancellation reason','Cancelled','Overpayment applied','Overpayment from {month}','Invoice amount','Amount due','Invoice cancelled; amount restored to the balance'],
  pl: ['Nadpłaty','Nadpłata jest automatycznie zaliczana na nową fakturę za późniejszy miesiąc dla dziecka tego samego płatnika. Kwota, powód i administrator są zapisywane.','Opłacona faktura', ...extra.pl,'Nadpłata (€)','Powód nadpłaty','Przenieś nadpłatę','Historia nadpłat','Brak nadpłat.','Wykorzystano','Pozostało','Anuluj nadpłatę','Powód anulowania','Anulowano','Zaliczona nadpłata','Nadpłata z {month}','Kwota faktury','Do zapłaty','Faktura anulowana; kwota przywrócona do salda'],
  lv: ['Pārmaksas','Pārmaksa tiek automātiski ieskaitīta jaunā rēķinā par vēlāku mēnesi tā paša maksātāja bērnam. Summa, iemesls un administrators tiek saglabāti.','Apmaksāts rēķins', ...extra.lv,'Pārmaksa (€)','Pārmaksas iemesls','Pārnest pārmaksu','Pārmaksu vēsture','Pārmaksu nav.','Izmantots','Atlikums','Atcelt pārmaksu','Atcelšanas iemesls','Atcelts','Ieskaitītā pārmaksa','Pārmaksa no {month}','Rēķina summa','Jāmaksā','Rēķins atcelts; summa atjaunota atlikumā'],
  ee: ['Enammaksed','Enammakse arvestatakse automaatselt sama maksja lapse uue, hilisema kuu arve katteks. Summa, põhjus ja administraator salvestatakse.','Makstud arve', ...extra.ee,'Enammakse (€)','Enammakse põhjus','Kanna enammakse üle','Enammaksete ajalugu','Enammakseid pole.','Kasutatud','Jääk','Tühista enammakse','Tühistamise põhjus','Tühistatud','Arvestatud enammakse','Enammakse {month}','Arve summa','Tasuda','Arve tühistatud; summa taastatud jäägis'],
  fr: ['Trop-perçus','Le trop-perçu est automatiquement déduit d’une nouvelle facture pour un mois ultérieur pour l’enfant du même payeur. Le montant, le motif et l’administrateur sont enregistrés.','Facture payée', ...extra.fr,'Trop-perçu (€)','Motif du trop-perçu','Reporter le trop-perçu','Historique des trop-perçus','Aucun trop-perçu.','Utilisé','Solde','Annuler le trop-perçu','Motif de l’annulation','Annulé','Trop-perçu déduit','Trop-perçu de {month}','Montant de la facture','À payer','Facture annulée ; montant rétabli dans le solde'],
  es: ['Pagos en exceso','El pago en exceso se aplica automáticamente a una nueva factura de un mes posterior para el hijo del mismo pagador. Se registran el importe, el motivo y el administrador.','Factura pagada', ...extra.es,'Pago en exceso (€)','Motivo del pago en exceso','Trasladar el saldo','Historial de pagos en exceso','No hay pagos en exceso.','Utilizado','Saldo','Cancelar el saldo','Motivo de cancelación','Cancelado','Saldo aplicado','Pago en exceso de {month}','Importe de la factura','A pagar','Factura cancelada; importe devuelto al saldo'],
  de: ['Überzahlungen','Die Überzahlung wird automatisch auf eine neue Rechnung für einen späteren Monat für das Kind desselben Zahlers angerechnet. Betrag, Grund und Administrator werden gespeichert.','Bezahlte Rechnung', ...extra.de,'Überzahlung (€)','Grund der Überzahlung','Überzahlung übertragen','Verlauf der Überzahlungen','Keine Überzahlungen.','Verwendet','Restbetrag','Überzahlung stornieren','Stornierungsgrund','Storniert','Angerechnete Überzahlung','Überzahlung aus {month}','Rechnungsbetrag','Zu zahlen','Rechnung storniert; Betrag wieder gutgeschrieben'],
  se: ['Överbetalningar','Överbetalningen räknas automatiskt av från en ny faktura för en senare månad för samma betalares barn. Belopp, orsak och administratör sparas.','Betald faktura', ...extra.se,'Överbetalning (€)','Orsak till överbetalning','För över överbetalning','Överbetalningshistorik','Inga överbetalningar.','Använt','Återstående','Avbryt överbetalning','Orsak till avbokning','Avbruten','Avräknad överbetalning','Överbetalning från {month}','Fakturabelopp','Att betala','Fakturan avbruten; beloppet återfört till saldot'],
  dk: ['Overbetalinger','Overbetalingen modregnes automatisk på en ny faktura for en senere måned for samme betalers barn. Beløb, årsag og administrator gemmes.','Betalt faktura', ...extra.dk,'Overbetaling (€)','Årsag til overbetaling','Overfør overbetaling','Overbetalingshistorik','Ingen overbetalinger.','Anvendt','Resterende','Annuller overbetaling','Årsag til annullering','Annulleret','Modregnet overbetaling','Overbetaling fra {month}','Fakturabeløb','Til betaling','Faktura annulleret; beløbet tilbageført til saldoen'],
  fi: ['Liikamaksut','Liikamaksu käytetään automaattisesti saman maksajan lapsen uuden, myöhemmän kuukauden laskuun. Summa, syy ja ylläpitäjä tallennetaan.','Maksettu lasku', ...extra.fi,'Liikamaksu (€)','Liikamaksun syy','Siirrä liikamaksu','Liikamaksuhistoria','Ei liikamaksuja.','Käytetty','Jäljellä','Peru liikamaksu','Peruutuksen syy','Peruttu','Hyvitetty liikamaksu','Liikamaksu {month}','Laskun summa','Maksettavaa','Lasku peruttu; summa palautettu saldoon'],
  no: ['Overbetalinger','Overbetalingen trekkes automatisk fra en ny faktura for en senere måned for samme betalers barn. Beløp, årsak og administrator lagres.','Betalt faktura', ...extra.no,'Overbetaling (€)','Årsak til overbetaling','Overfør overbetaling','Overbetalingshistorikk','Ingen overbetalinger.','Brukt','Gjenstående','Avbryt overbetaling','Årsak til avbestilling','Avbrutt','Avregnet overbetaling','Overbetaling fra {month}','Fakturabeløp','Å betale','Faktura avbrutt; beløpet tilbakeført til saldoen'],
  nl: ['Te veel betaalde bedragen','Het teveel betaalde bedrag wordt automatisch verrekend met een nieuwe factuur voor een latere maand voor het kind van dezelfde betaler. Bedrag, reden en beheerder worden vastgelegd.','Betaalde factuur', ...extra.nl,'Te veel betaald (€)','Reden van overbetaling','Bedrag overdragen','Historie van overbetalingen','Geen overbetalingen.','Gebruikt','Resterend','Overbetaling annuleren','Reden van annulering','Geannuleerd','Verrekende overbetaling','Overbetaling van {month}','Factuurbedrag','Te betalen','Factuur geannuleerd; bedrag teruggezet op het saldo'],
};
export const schoolInvoiceOverpaymentTranslations: Record<string, Record<string, string>> = Object.fromEntries(
  Object.entries(copy).map(([locale, values]) => {
    if (values.length !== keys.length) throw new Error(`Incomplete overpayment translation: ${locale}`);
    return [locale, Object.fromEntries(keys.map((key, index) => [`school.invoice.credit.${key}`, values[index]]))];
  }),
);
