import type { Locale } from './locales.js';

const keys = [
  'school.materials.title', 'school.materials.digestSubject', 'school.materials.digestBody',
  'school.materials.open', 'school.materials.pickChild', 'school.materials.recordings',
  'school.materials.homework', 'school.materials.noFiles', 'school.materials.noChildren',
  'school.materials.privateHint', 'school.materials.baselineTitle', 'school.materials.baselineHelp',
  'school.materials.prepareBaseline', 'school.materials.baselineReady', 'school.materials.baselinePending',
  'school.materials.baselineFailed', 'school.materials.baselineFirst',
  'school.recordingPlan.label', 'school.recordingPlan.schedule', 'school.recordingPlan.group',
  'school.recordingPlan.none', 'school.recordingPlan.contractHint', 'school.recordingPlan.withoutHint',
  'school.recordingPlan.oneWeekly', 'school.recordingPlan.termsLabel',
] as const;

const values: Partial<Record<Locale, string[]>> = {
  lt: ['Namų darbai ir įrašai', 'Nauja mokymosi medžiaga · {date}', 'Viename laiške rasite naujų įrašų ir namų darbų sąrašą. Medžiagą atidarykite prisijungę prie paskyros.', 'Atidaryti medžiagą', 'Pasirinkite vaiką', 'Pamokų įrašai', 'Namų darbai', 'Naujos medžiagos dar nėra.', 'Prieinamų vaikų nerasta. Kreipkitės į mokyklą.', 'Naują medžiagą peržiūrėkite prisijungę prie Tutlio.', 'Šeimos paskyrų medžiaga', 'Prieš įjungdami šeimos paskyrų prieigą išsaugokite senų bendrų nuorodų apimtį. Drive failai išlieka savo aplankuose.', 'Paruošti senų nuorodų prieigą', 'Senų nuorodų prieiga paruošta.', 'Tęskite paruošimą.', 'Nepavyko paruošti prieigos. Patikrinkite Drive ryšį ir bandykite dar kartą.', 'Pirmiausia paruoškite medžiagos prieigą administracijos paskyroje.', 'Prieiga prie įrašų', 'Pagal lankomus grupės laikus', 'Su visos grupės įrašais', 'Be įrašų', 'Galiojančios sutartys išsaugo jose numatytą prieigą prie įrašų.', 'Pasirinkite vieną grupės užsiėmimą per savaitę ir sutartą kainą. Įrašai į šį planą neįtraukti.', 'Vienas grupės užsiėmimas per savaitę', 'Įrašų prieiga'],
  en: ['Homework and recordings', 'New learning materials · {date}', 'Your new recordings and homework are collected in one email. Sign in to your account to open the materials.', 'Open materials', 'Choose a child', 'Lesson recordings', 'Homework', 'No new materials yet.', 'No accessible children found. Contact the school.', 'Sign in to Tutlio to view new materials.', 'Family account materials', 'Before enabling family access, preserve the scope of existing shared links. Drive files stay in their folders.', 'Prepare existing link access', 'Existing link access is ready.', 'Continue preparation.', 'Could not prepare access. Check the Drive connection and try again.', 'Prepare material access in the administration account first.', 'Recording access', 'Based on attended group times', 'All group recordings included', 'Without recordings', 'Existing contracts retain their agreed recording access.', 'Choose one weekly group lesson and the agreed price. Recordings are excluded from this plan.', 'One group lesson per week', 'Recording access'],
  pl: ['Zadania domowe i nagrania', 'Nowe materiały do nauki · {date}', 'Nowe nagrania i zadania domowe znajdują się w jednym e-mailu. Zaloguj się, aby otworzyć materiały.', 'Otwórz materiały', 'Wybierz dziecko', 'Nagrania lekcji', 'Zadania domowe', 'Nie ma jeszcze nowych materiałów.', 'Brak dostępnych dzieci. Skontaktuj się ze szkołą.', 'Zaloguj się do Tutlio, aby zobaczyć nowe materiały.', 'Materiały kont rodzinnych', 'Przed włączeniem dostępu rodzinnego zachowaj zakres istniejących wspólnych linków. Pliki Drive pozostają w swoich folderach.', 'Przygotuj dostęp ze starych linków', 'Dostęp ze starych linków jest gotowy.', 'Kontynuuj przygotowanie.', 'Nie udało się przygotować dostępu. Sprawdź połączenie z Drive i spróbuj ponownie.', 'Najpierw przygotuj dostęp do materiałów na koncie administratora.', 'Dostęp do nagrań', 'Według godzin zajęć grupowych', 'Wszystkie nagrania grupy', 'Bez nagrań', 'Obowiązujące umowy zachowują uzgodniony dostęp do nagrań.', 'Wybierz jedną lekcję grupową w tygodniu i uzgodnioną cenę. Ten plan nie obejmuje nagrań.', 'Jedna lekcja grupowa w tygodniu', 'Dostęp do nagrań'],
  de: ['Hausaufgaben und Aufzeichnungen', 'Neue Lernmaterialien · {date}', 'Neue Aufzeichnungen und Hausaufgaben sind in einer E-Mail zusammengefasst. Melden Sie sich an, um die Materialien zu öffnen.', 'Materialien öffnen', 'Kind auswählen', 'Unterrichtsaufzeichnungen', 'Hausaufgaben', 'Noch keine neuen Materialien.', 'Keine zugänglichen Kinder gefunden. Kontaktieren Sie die Schule.', 'Melden Sie sich bei Tutlio an, um neue Materialien anzusehen.', 'Materialien für Familienkonten', 'Sichern Sie vor der Aktivierung des Familienzugangs den Umfang bestehender Freigabelinks. Drive-Dateien bleiben in ihren Ordnern.', 'Bestehende Linkzugriffe vorbereiten', 'Bestehende Linkzugriffe sind vorbereitet.', 'Vorbereitung fortsetzen.', 'Zugriff konnte nicht vorbereitet werden. Prüfen Sie die Drive-Verbindung und versuchen Sie es erneut.', 'Bereiten Sie zuerst den Materialzugang im Administrationskonto vor.', 'Zugriff auf Aufzeichnungen', 'Nach besuchten Gruppenzeiten', 'Alle Gruppenaufzeichnungen', 'Ohne Aufzeichnungen', 'Bestehende Verträge behalten den vereinbarten Zugriff auf Aufzeichnungen.', 'Wählen Sie eine Gruppenstunde pro Woche und den vereinbarten Preis. Dieser Plan enthält keine Aufzeichnungen.', 'Eine Gruppenstunde pro Woche', 'Zugriff auf Aufzeichnungen'],
  fr: ['Devoirs et enregistrements', 'Nouveaux supports pédagogiques · {date}', 'Les nouveaux enregistrements et devoirs sont réunis dans un seul e-mail. Connectez-vous pour ouvrir les supports.', 'Ouvrir les supports', 'Choisir un enfant', 'Enregistrements des cours', 'Devoirs', 'Aucun nouveau support pour le moment.', 'Aucun enfant accessible. Contactez l’établissement.', 'Connectez-vous à Tutlio pour consulter les nouveaux supports.', 'Supports des comptes familiaux', 'Avant d’activer l’accès familial, conservez la portée des liens partagés existants. Les fichiers Drive restent dans leurs dossiers.', 'Préparer l’accès des anciens liens', 'L’accès des anciens liens est prêt.', 'Continuer la préparation.', 'Impossible de préparer l’accès. Vérifiez la connexion Drive et réessayez.', 'Préparez d’abord l’accès aux supports depuis le compte administrateur.', 'Accès aux enregistrements', 'Selon les horaires de groupe suivis', 'Tous les enregistrements du groupe', 'Sans enregistrements', 'Les contrats en vigueur conservent l’accès aux enregistrements convenu.', 'Choisissez un cours collectif par semaine et le tarif convenu. Ce forfait ne comprend pas les enregistrements.', 'Un cours collectif par semaine', 'Accès aux enregistrements'],
  es: ['Tareas y grabaciones', 'Nuevos materiales de aprendizaje · {date}', 'Las nuevas grabaciones y tareas están reunidas en un solo correo. Inicia sesión para abrir los materiales.', 'Abrir materiales', 'Elegir un hijo', 'Grabaciones de clases', 'Tareas', 'Todavía no hay materiales nuevos.', 'No se encontraron hijos accesibles. Contacta con el centro.', 'Inicia sesión en Tutlio para ver materiales nuevos.', 'Materiales de cuentas familiares', 'Antes de activar el acceso familiar, conserva el alcance de los enlaces compartidos existentes. Los archivos de Drive permanecen en sus carpetas.', 'Preparar acceso de enlaces anteriores', 'El acceso de enlaces anteriores está listo.', 'Continuar preparación.', 'No se pudo preparar el acceso. Comprueba la conexión con Drive e inténtalo de nuevo.', 'Primero prepara el acceso a materiales desde la cuenta de administración.', 'Acceso a grabaciones', 'Según los horarios de grupo asistidos', 'Todas las grabaciones del grupo', 'Sin grabaciones', 'Los contratos vigentes conservan el acceso acordado a las grabaciones.', 'Elige una clase de grupo semanal y el precio acordado. Este plan no incluye grabaciones.', 'Una clase de grupo por semana', 'Acceso a grabaciones'],
  lv: ['Mājasdarbi un ieraksti', 'Jauni mācību materiāli · {date}', 'Jaunie ieraksti un mājasdarbi ir apkopoti vienā e-pastā. Piesakieties kontā, lai atvērtu materiālus.', 'Atvērt materiālus', 'Izvēlieties bērnu', 'Nodarbību ieraksti', 'Mājasdarbi', 'Jaunu materiālu vēl nav.', 'Pieejami bērni nav atrasti. Sazinieties ar skolu.', 'Piesakieties Tutlio, lai skatītu jaunus materiālus.', 'Ģimenes kontu materiāli', 'Pirms ģimenes piekļuves ieslēgšanas saglabājiet esošo kopīgo saišu piekļuves apjomu. Drive faili paliek savās mapēs.', 'Sagatavot veco saišu piekļuvi', 'Veco saišu piekļuve ir sagatavota.', 'Turpināt sagatavošanu.', 'Neizdevās sagatavot piekļuvi. Pārbaudiet Drive savienojumu un mēģiniet vēlreiz.', 'Vispirms sagatavojiet materiālu piekļuvi administratora kontā.', 'Piekļuve ierakstiem', 'Pēc apmeklētajiem grupas laikiem', 'Ar visiem grupas ierakstiem', 'Bez ierakstiem', 'Spēkā esošie līgumi saglabā tajos noteikto piekļuvi ierakstiem.', 'Izvēlieties vienu grupas nodarbību nedēļā un saskaņoto cenu. Šajā plānā ieraksti nav iekļauti.', 'Viena grupas nodarbība nedēļā', 'Piekļuve ierakstiem'],
  ee: ['Kodutööd ja salvestused', 'Uued õppematerjalid · {date}', 'Uued salvestused ja kodutööd on koondatud ühte e-kirja. Materjalide avamiseks logige kontole sisse.', 'Ava materjalid', 'Vali laps', 'Tundide salvestused', 'Kodutööd', 'Uusi materjale veel ei ole.', 'Ligipääsetavaid lapsi ei leitud. Võtke kooliga ühendust.', 'Uute materjalide vaatamiseks logige Tutliosse sisse.', 'Perekontode materjalid', 'Enne pere ligipääsu aktiveerimist säilitage olemasolevate jagatud linkide ulatus. Drive’i failid jäävad oma kaustadesse.', 'Valmista ette vanade linkide ligipääs', 'Vanade linkide ligipääs on valmis.', 'Jätka ettevalmistust.', 'Ligipääsu ei saanud ette valmistada. Kontrollige Drive’i ühendust ja proovige uuesti.', 'Valmistage materjalide ligipääs esmalt administraatorikontol ette.', 'Ligipääs salvestustele', 'Osaletud rühmaaegade järgi', 'Kõik rühma salvestused', 'Ilma salvestusteta', 'Kehtivad lepingud säilitavad kokkulepitud ligipääsu salvestustele.', 'Valige üks rühmatund nädalas ja kokkulepitud hind. See plaan ei sisalda salvestusi.', 'Üks rühmatund nädalas', 'Ligipääs salvestustele'],
  fi: ['Kotitehtävät ja tallenteet', 'Uudet oppimateriaalit · {date}', 'Uudet tallenteet ja kotitehtävät on koottu yhteen sähköpostiin. Kirjaudu tilillesi avataksesi materiaalit.', 'Avaa materiaalit', 'Valitse lapsi', 'Oppituntien tallenteet', 'Kotitehtävät', 'Ei vielä uusia materiaaleja.', 'Lapsia ei löytynyt. Ota yhteyttä kouluun.', 'Kirjaudu Tutlioon nähdäksesi uudet materiaalit.', 'Perhetilien materiaalit', 'Säilytä nykyisten jaettujen linkkien käyttöoikeudet ennen perhekäytön käyttöönottoa. Drive-tiedostot pysyvät kansioissaan.', 'Valmistele vanhojen linkkien käyttö', 'Vanhojen linkkien käyttö on valmis.', 'Jatka valmistelua.', 'Käyttöä ei voitu valmistella. Tarkista Drive-yhteys ja yritä uudelleen.', 'Valmistele ensin materiaalien käyttö ylläpitäjän tilillä.', 'Tallenteiden käyttö', 'Osallistuttujen ryhmäaikojen mukaan', 'Kaikki ryhmän tallenteet', 'Ilman tallenteita', 'Voimassa olevat sopimukset säilyttävät sovitut tallenteiden käyttöoikeudet.', 'Valitse yksi ryhmätunti viikossa ja sovittu hinta. Tämä suunnitelma ei sisällä tallenteita.', 'Yksi ryhmätunti viikossa', 'Tallenteiden käyttö'],
  se: ['Läxor och inspelningar', 'Nytt undervisningsmaterial · {date}', 'Nya inspelningar och läxor samlas i ett mejl. Logga in på ditt konto för att öppna materialet.', 'Öppna material', 'Välj barn', 'Lektionsinspelningar', 'Läxor', 'Inget nytt material ännu.', 'Inga tillgängliga barn hittades. Kontakta skolan.', 'Logga in på Tutlio för att se nytt material.', 'Material för familjekonton', 'Bevara befintliga delade länkars åtkomst innan familjeåtkomst aktiveras. Drive-filer stannar i sina mappar.', 'Förbered gamla länkars åtkomst', 'Gamla länkars åtkomst är klar.', 'Fortsätt förberedelsen.', 'Kunde inte förbereda åtkomst. Kontrollera Drive-anslutningen och försök igen.', 'Förbered först materialåtkomst i administratörskontot.', 'Åtkomst till inspelningar', 'Efter deltagna grupptider', 'Alla gruppens inspelningar', 'Utan inspelningar', 'Gällande avtal behåller överenskommen åtkomst till inspelningar.', 'Välj en grupplektion per vecka och överenskommet pris. Inspelningar ingår inte i denna plan.', 'En grupplektion per vecka', 'Åtkomst till inspelningar'],
  no: ['Lekser og opptak', 'Nytt læremateriell · {date}', 'Nye opptak og lekser samles i én e-post. Logg inn på kontoen din for å åpne materialet.', 'Åpne materiell', 'Velg barn', 'Leksjonsopptak', 'Lekser', 'Ingen nye materialer ennå.', 'Ingen tilgjengelige barn funnet. Kontakt skolen.', 'Logg inn på Tutlio for å se nye materialer.', 'Materiell for familiekontoer', 'Bevar tilgangen fra eksisterende delte lenker før familietilgang aktiveres. Drive-filer blir i sine mapper.', 'Forbered gamle lenkers tilgang', 'Gamle lenkers tilgang er klar.', 'Fortsett forberedelsen.', 'Kunne ikke forberede tilgang. Kontroller Drive-tilkoblingen og prøv igjen.', 'Forbered først materialtilgang i administratorkontoen.', 'Tilgang til opptak', 'Etter gruppetidene eleven deltar på', 'Alle gruppens opptak', 'Uten opptak', 'Gjeldende avtaler beholder avtalt tilgang til opptak.', 'Velg én gruppetime per uke og avtalt pris. Opptak er ikke inkludert i denne planen.', 'Én gruppetime per uke', 'Tilgang til opptak'],
  dk: ['Lektier og optagelser', 'Nyt undervisningsmateriale · {date}', 'Nye optagelser og lektier samles i én e-mail. Log ind på din konto for at åbne materialet.', 'Åbn materiale', 'Vælg barn', 'Lektionsoptagelser', 'Lektier', 'Intet nyt materiale endnu.', 'Ingen tilgængelige børn fundet. Kontakt skolen.', 'Log ind på Tutlio for at se nyt materiale.', 'Materiale til familiekonti', 'Bevar adgangen fra eksisterende delte links, før familieadgang aktiveres. Drive-filer bliver i deres mapper.', 'Forbered gamle links adgang', 'Gamle links adgang er klar.', 'Fortsæt forberedelsen.', 'Kunne ikke forberede adgang. Kontroller Drive-forbindelsen, og prøv igen.', 'Forbered først materialeadgang i administratorkontoen.', 'Adgang til optagelser', 'Efter de gruppetider eleven deltager i', 'Alle gruppens optagelser', 'Uden optagelser', 'Gældende aftaler beholder den aftalte adgang til optagelser.', 'Vælg én gruppetime om ugen og den aftalte pris. Optagelser indgår ikke i denne plan.', 'Én gruppetime om ugen', 'Adgang til optagelser'],
  nl: ['Huiswerk en opnamen', 'Nieuw lesmateriaal · {date}', 'Nieuwe opnamen en huiswerk staan samen in één e-mail. Log in op je account om het materiaal te openen.', 'Materiaal openen', 'Kies een kind', 'Lesopnamen', 'Huiswerk', 'Nog geen nieuw materiaal.', 'Geen toegankelijke kinderen gevonden. Neem contact op met de school.', 'Log in bij Tutlio om nieuw materiaal te bekijken.', 'Materiaal voor gezinsaccounts', 'Bewaar de toegang van bestaande gedeelde links voordat gezinstoegang wordt ingeschakeld. Drive-bestanden blijven in hun mappen.', 'Toegang van oude links voorbereiden', 'Toegang van oude links is klaar.', 'Ga verder met voorbereiden.', 'De toegang kon niet worden voorbereid. Controleer de Drive-verbinding en probeer opnieuw.', 'Bereid eerst de toegang tot materiaal voor via het beheerdersaccount.', 'Toegang tot opnamen', 'Volgens de bijgewoonde groepstijden', 'Alle groepsopnamen inbegrepen', 'Zonder opnamen', 'Bestaande overeenkomsten behouden de afgesproken toegang tot opnamen.', 'Kies één groepsles per week en de afgesproken prijs. Opnamen zijn niet inbegrepen in dit plan.', 'Eén groepsles per week', 'Toegang tot opnamen'],
};

export const schoolFamilyMaterialTranslations = Object.fromEntries(Object.entries(values).map(([locale, texts]) =>
  [locale, Object.fromEntries(keys.map((key, index) => [key, texts[index]]))],
)) as Record<Locale, Record<string, string>>;
