const keys = ['view', 'confidentiality', 'annex', 'consent', 'draftHint', 'reviewHint', 'loadError'] as const;

const copy = {
  lt: ['Peržiūrėti dokumentą', 'Konfidencialumo susitarimas su priedu', 'Konfidencialios informacijos sąrašo priedas', 'Asmens duomenų tvarkymo sutikimas', 'Tai visas dokumento tekstas. Trūkstami duomenys ir pasirinkimai bus įrašyti prieš pasirašymą. Peržiūra nėra parašas.', 'Prieš pateikdami duomenis ir pasirinkimus galite perskaityti abu dokumentus.', 'Nepavyko įkelti dokumento peržiūros. Bandykite dar kartą.'],
  en: ['View document', 'Confidentiality agreement with annex', 'Confidential information list annex', 'Personal data processing consent', 'This is the full document text. Missing details and choices will be filled in before signing. Viewing is not signing.', 'You can read both documents before submitting your details and choices.', 'Could not load the document preview. Please try again.'],
  pl: ['Zobacz dokument', 'Umowa o poufności z załącznikiem', 'Załącznik z wykazem informacji poufnych', 'Zgoda na przetwarzanie danych osobowych', 'To pełna treść dokumentu. Brakujące dane i wybory zostaną uzupełnione przed podpisaniem. Przeglądanie nie oznacza podpisania.', 'Przed przesłaniem danych i wyborów możesz przeczytać oba dokumenty.', 'Nie udało się załadować podglądu dokumentu. Spróbuj ponownie.'],
  lv: ['Apskatīt dokumentu', 'Konfidencialitātes vienošanās ar pielikumu', 'Konfidenciālās informācijas saraksta pielikums', 'Piekrišana personas datu apstrādei', 'Šis ir pilns dokumenta teksts. Trūkstošie dati un izvēles tiks aizpildīti pirms parakstīšanas. Apskatīšana nav parakstīšana.', 'Pirms datu un izvēļu iesniegšanas varat izlasīt abus dokumentus.', 'Neizdevās ielādēt dokumenta priekšskatījumu. Mēģiniet vēlreiz.'],
  ee: ['Vaata dokumenti', 'Konfidentsiaalsuskokkulepe koos lisaga', 'Konfidentsiaalse teabe loetelu lisa', 'Isikuandmete töötlemise nõusolek', 'See on dokumendi täielik tekst. Puuduvad andmed ja valikud täidetakse enne allkirjastamist. Vaatamine ei ole allkirjastamine.', 'Enne andmete ja valikute esitamist saate lugeda mõlemat dokumenti.', 'Dokumendi eelvaate laadimine ebaõnnestus. Proovige uuesti.'],
  fr: ['Voir le document', 'Accord de confidentialité avec annexe', 'Annexe de la liste des informations confidentielles', 'Consentement au traitement des données personnelles', 'Voici le texte intégral du document. Les informations et choix manquants seront renseignés avant la signature. Consulter ne vaut pas signature.', 'Vous pouvez lire les deux documents avant de transmettre vos informations et vos choix.', 'Impossible de charger l’aperçu du document. Veuillez réessayer.'],
  es: ['Ver documento', 'Acuerdo de confidencialidad con anexo', 'Anexo con la lista de información confidencial', 'Consentimiento para el tratamiento de datos personales', 'Este es el texto completo del documento. Los datos y las opciones que falten se completarán antes de firmar. Consultar no equivale a firmar.', 'Puedes leer ambos documentos antes de enviar tus datos y opciones.', 'No se pudo cargar la vista previa del documento. Inténtalo de nuevo.'],
  de: ['Dokument ansehen', 'Vertraulichkeitsvereinbarung mit Anlage', 'Anlage mit dem Verzeichnis vertraulicher Informationen', 'Einwilligung zur Verarbeitung personenbezogener Daten', 'Dies ist der vollständige Dokumenttext. Fehlende Angaben und Entscheidungen werden vor der Unterzeichnung ergänzt. Ansehen gilt nicht als Unterzeichnung.', 'Sie können beide Dokumente lesen, bevor Sie Ihre Angaben und Entscheidungen übermitteln.', 'Die Dokumentvorschau konnte nicht geladen werden. Bitte versuchen Sie es erneut.'],
  se: ['Visa dokument', 'Sekretessavtal med bilaga', 'Bilaga med förteckning över konfidentiell information', 'Samtycke till behandling av personuppgifter', 'Detta är dokumentets fullständiga text. Saknade uppgifter och val fylls i före undertecknandet. Att läsa är inte att underteckna.', 'Du kan läsa båda dokumenten innan du skickar in dina uppgifter och val.', 'Dokumentförhandsvisningen kunde inte laddas. Försök igen.'],
  dk: ['Vis dokument', 'Fortrolighedsaftale med bilag', 'Bilag med liste over fortrolige oplysninger', 'Samtykke til behandling af personoplysninger', 'Dette er dokumentets fulde tekst. Manglende oplysninger og valg udfyldes før underskrift. At læse er ikke at underskrive.', 'Du kan læse begge dokumenter, før du indsender dine oplysninger og valg.', 'Dokumentvisningen kunne ikke indlæses. Prøv igen.'],
  fi: ['Näytä asiakirja', 'Salassapitosopimus liitteineen', 'Luottamuksellisten tietojen luetteloliite', 'Suostumus henkilötietojen käsittelyyn', 'Tämä on asiakirjan koko teksti. Puuttuvat tiedot ja valinnat täytetään ennen allekirjoittamista. Lukeminen ei ole allekirjoittamista.', 'Voit lukea molemmat asiakirjat ennen tietojesi ja valintojesi lähettämistä.', 'Asiakirjan esikatselua ei voitu ladata. Yritä uudelleen.'],
  no: ['Vis dokument', 'Konfidensialitetsavtale med vedlegg', 'Vedlegg med liste over konfidensiell informasjon', 'Samtykke til behandling av personopplysninger', 'Dette er hele dokumentteksten. Manglende opplysninger og valg fylles ut før signering. Å lese er ikke å signere.', 'Du kan lese begge dokumentene før du sender inn opplysninger og valg.', 'Kunne ikke laste dokumentforhåndsvisningen. Prøv igjen.'],
  nl: ['Document bekijken', 'Geheimhoudingsovereenkomst met bijlage', 'Bijlage met lijst van vertrouwelijke informatie', 'Toestemming voor verwerking van persoonsgegevens', 'Dit is de volledige documenttekst. Ontbrekende gegevens en keuzes worden vóór ondertekening ingevuld. Bekijken is geen ondertekening.', 'Je kunt beide documenten lezen voordat je je gegevens en keuzes indient.', 'Het documentvoorbeeld kon niet worden geladen. Probeer het opnieuw.'],
} satisfies Record<string, [string, string, string, string, string, string, string]>;

export const schoolStaffPreviewTranslations = Object.fromEntries(
  Object.entries(copy).map(([locale, values]) => [locale, Object.fromEntries(
    keys.map((key, index) => [`school.staffPreview.${key}`, values[index]]),
  )]),
) as Record<keyof typeof copy, Record<string, string>>;
