const keys = ['title','help','source','amount','reason','save','history','empty','used','remaining','void','voidReason','voided','applied','total','due','released'] as const;
const copy: Record<string, string[]> = {
  lt: ['Permokos','Permoka automatiškai užskaitoma naujai to paties mokėtojo vaiko sąskaitai už vėlesnį mėnesį. Suma, priežastis ir administratorius išsaugomi istorijoje.','Apmokėta sąskaita','Permoka (€)','Permokos priežastis','Perkelti permoką','Permokų istorija','Permokų nėra.','Panaudota','Likutis','Atšaukti permoką','Atšaukimo priežastis','Atšaukta','Užskaityta permoka','Sąskaitos suma','Mokėti','Sąskaita atšaukta; suma grąžinta į likutį'],
  en: ['Overpayments','An overpayment is automatically applied to a new invoice for a later month for the same payer’s child. The amount, reason and administrator are recorded.','Paid invoice','Overpayment (€)','Overpayment reason','Carry over payment','Overpayment history','No overpayments.','Used','Remaining','Cancel overpayment','Cancellation reason','Cancelled','Overpayment applied','Invoice amount','Amount due','Invoice cancelled; amount restored to the balance'],
  pl: ['Nadpłaty','Nadpłata jest automatycznie zaliczana na nową fakturę za późniejszy miesiąc dla dziecka tego samego płatnika. Kwota, powód i administrator są zapisywane.','Opłacona faktura','Nadpłata (€)','Powód nadpłaty','Przenieś nadpłatę','Historia nadpłat','Brak nadpłat.','Wykorzystano','Pozostało','Anuluj nadpłatę','Powód anulowania','Anulowano','Zaliczona nadpłata','Kwota faktury','Do zapłaty','Faktura anulowana; kwota przywrócona do salda'],
  lv: ['Pārmaksas','Pārmaksa tiek automātiski ieskaitīta jaunā rēķinā par vēlāku mēnesi tā paša maksātāja bērnam. Summa, iemesls un administrators tiek saglabāti.','Apmaksāts rēķins','Pārmaksa (€)','Pārmaksas iemesls','Pārnest pārmaksu','Pārmaksu vēsture','Pārmaksu nav.','Izmantots','Atlikums','Atcelt pārmaksu','Atcelšanas iemesls','Atcelts','Ieskaitītā pārmaksa','Rēķina summa','Jāmaksā','Rēķins atcelts; summa atjaunota atlikumā'],
  ee: ['Enammaksed','Enammakse arvestatakse automaatselt sama maksja lapse uue, hilisema kuu arve katteks. Summa, põhjus ja administraator salvestatakse.','Makstud arve','Enammakse (€)','Enammakse põhjus','Kanna enammakse üle','Enammaksete ajalugu','Enammakseid pole.','Kasutatud','Jääk','Tühista enammakse','Tühistamise põhjus','Tühistatud','Arvestatud enammakse','Arve summa','Tasuda','Arve tühistatud; summa taastatud jäägis'],
  fr: ['Trop-perçus','Le trop-perçu est automatiquement déduit d’une nouvelle facture pour un mois ultérieur pour l’enfant du même payeur. Le montant, le motif et l’administrateur sont enregistrés.','Facture payée','Trop-perçu (€)','Motif du trop-perçu','Reporter le trop-perçu','Historique des trop-perçus','Aucun trop-perçu.','Utilisé','Solde','Annuler le trop-perçu','Motif de l’annulation','Annulé','Trop-perçu déduit','Montant de la facture','À payer','Facture annulée ; montant rétabli dans le solde'],
  es: ['Pagos en exceso','El pago en exceso se aplica automáticamente a una nueva factura de un mes posterior para el hijo del mismo pagador. Se registran el importe, el motivo y el administrador.','Factura pagada','Pago en exceso (€)','Motivo del pago en exceso','Trasladar el saldo','Historial de pagos en exceso','No hay pagos en exceso.','Utilizado','Saldo','Cancelar el saldo','Motivo de cancelación','Cancelado','Saldo aplicado','Importe de la factura','A pagar','Factura cancelada; importe devuelto al saldo'],
  de: ['Überzahlungen','Die Überzahlung wird automatisch auf eine neue Rechnung für einen späteren Monat für das Kind desselben Zahlers angerechnet. Betrag, Grund und Administrator werden gespeichert.','Bezahlte Rechnung','Überzahlung (€)','Grund der Überzahlung','Überzahlung übertragen','Verlauf der Überzahlungen','Keine Überzahlungen.','Verwendet','Restbetrag','Überzahlung stornieren','Stornierungsgrund','Storniert','Angerechnete Überzahlung','Rechnungsbetrag','Zu zahlen','Rechnung storniert; Betrag wieder gutgeschrieben'],
  se: ['Överbetalningar','Överbetalningen räknas automatiskt av från en ny faktura för en senare månad för samma betalares barn. Belopp, orsak och administratör sparas.','Betald faktura','Överbetalning (€)','Orsak till överbetalning','För över överbetalning','Överbetalningshistorik','Inga överbetalningar.','Använt','Återstående','Avbryt överbetalning','Orsak till avbokning','Avbruten','Avräknad överbetalning','Fakturabelopp','Att betala','Fakturan avbruten; beloppet återfört till saldot'],
  dk: ['Overbetalinger','Overbetalingen modregnes automatisk på en ny faktura for en senere måned for samme betalers barn. Beløb, årsag og administrator gemmes.','Betalt faktura','Overbetaling (€)','Årsag til overbetaling','Overfør overbetaling','Overbetalingshistorik','Ingen overbetalinger.','Anvendt','Resterende','Annuller overbetaling','Årsag til annullering','Annulleret','Modregnet overbetaling','Fakturabeløb','Til betaling','Faktura annulleret; beløbet tilbageført til saldoen'],
  fi: ['Liikamaksut','Liikamaksu käytetään automaattisesti saman maksajan lapsen uuden, myöhemmän kuukauden laskuun. Summa, syy ja ylläpitäjä tallennetaan.','Maksettu lasku','Liikamaksu (€)','Liikamaksun syy','Siirrä liikamaksu','Liikamaksuhistoria','Ei liikamaksuja.','Käytetty','Jäljellä','Peru liikamaksu','Peruutuksen syy','Peruttu','Hyvitetty liikamaksu','Laskun summa','Maksettavaa','Lasku peruttu; summa palautettu saldoon'],
  no: ['Overbetalinger','Overbetalingen trekkes automatisk fra en ny faktura for en senere måned for samme betalers barn. Beløp, årsak og administrator lagres.','Betalt faktura','Overbetaling (€)','Årsak til overbetaling','Overfør overbetaling','Overbetalingshistorikk','Ingen overbetalinger.','Brukt','Gjenstående','Avbryt overbetaling','Årsak til avbestilling','Avbrutt','Avregnet overbetaling','Fakturabeløp','Å betale','Faktura avbrutt; beløpet tilbakeført til saldoen'],
  nl: ['Te veel betaalde bedragen','Het teveel betaalde bedrag wordt automatisch verrekend met een nieuwe factuur voor een latere maand voor het kind van dezelfde betaler. Bedrag, reden en beheerder worden vastgelegd.','Betaalde factuur','Te veel betaald (€)','Reden van overbetaling','Bedrag overdragen','Historie van overbetalingen','Geen overbetalingen.','Gebruikt','Resterend','Overbetaling annuleren','Reden van annulering','Geannuleerd','Verrekende overbetaling','Factuurbedrag','Te betalen','Factuur geannuleerd; bedrag teruggezet op het saldo'],
};
export const schoolInvoiceOverpaymentTranslations: Record<string, Record<string, string>> = Object.fromEntries(
  Object.entries(copy).map(([locale, values]) => {
    if (values.length !== keys.length) throw new Error(`Incomplete overpayment translation: ${locale}`);
    return [locale, Object.fromEntries(keys.map((key, index) => [`school.invoice.credit.${key}`, values[index]]))];
  }),
);
