create schema if not exists extensions;
create extension if not exists vector with schema extensions;

create table if not exists public.in_app_support_knowledge (
  id bigint generated by default as identity primary key,
  knowledge_key text not null unique,
  title text not null,
  content text not null,
  locale text not null default 'multi',
  portals text[] not null default '{}',
  entity_types text[] not null default '{}',
  feature_id text,
  required_permission text,
  organization_id uuid references public.organizations(id) on delete cascade,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(1536) not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint in_app_support_knowledge_portals check (
    portals <@ array['tutor', 'organization', 'student', 'parent']::text[]
  ),
  constraint in_app_support_knowledge_entity_types check (
    entity_types <@ array['company', 'school']::text[]
  )
);

create table if not exists public.in_app_support_memory (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id text not null,
  organization_id uuid references public.organizations(id) on delete cascade,
  portal text not null,
  content text not null,
  content_hash text not null,
  embedding extensions.vector(1536) not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  constraint in_app_support_memory_portal check (
    portal in ('tutor', 'organization', 'student', 'parent')
  ),
  constraint in_app_support_memory_conversation_length check (
    char_length(conversation_id) between 8 and 100
  ),
  constraint in_app_support_memory_content_length check (
    char_length(content) between 1 and 8000
  ),
  unique (user_id, conversation_id, content_hash)
);

comment on table public.in_app_support_knowledge is
  'Server-only support documentation. Optional function chunks are tagged so authorization filters run before vector ranking.';
comment on table public.in_app_support_memory is
  'Short-lived semantic memory scoped to one signed-in user, support conversation, and exact organization.';

create index if not exists in_app_support_knowledge_embedding_idx
  on public.in_app_support_knowledge
  using hnsw (embedding extensions.vector_cosine_ops);
create index if not exists in_app_support_knowledge_scope_idx
  on public.in_app_support_knowledge (organization_id, feature_id, required_permission)
  where is_active = true;
create index if not exists in_app_support_memory_embedding_idx
  on public.in_app_support_memory
  using hnsw (embedding extensions.vector_cosine_ops);
create index if not exists in_app_support_memory_scope_idx
  on public.in_app_support_memory (user_id, conversation_id, organization_id, expires_at desc);

alter table public.in_app_support_knowledge enable row level security;
alter table public.in_app_support_memory enable row level security;
revoke all on table public.in_app_support_knowledge from public, anon, authenticated;
revoke all on table public.in_app_support_memory from public, anon, authenticated;
grant select, insert, update, delete on table public.in_app_support_knowledge to service_role;
grant select, insert, update, delete on table public.in_app_support_memory to service_role;
grant usage, select on sequence public.in_app_support_knowledge_id_seq to service_role;
grant usage, select on sequence public.in_app_support_memory_id_seq to service_role;

create or replace function public.match_in_app_support_knowledge(
  query_embedding extensions.vector(1536),
  match_threshold double precision,
  match_count integer,
  filter_portal text,
  filter_entity_type text,
  filter_organization_id uuid,
  filter_feature_ids text[],
  filter_permissions text[]
)
returns table (
  knowledge_key text,
  title text,
  content text,
  similarity double precision
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  select
    knowledge.knowledge_key,
    knowledge.title,
    knowledge.content,
    (1 - (knowledge.embedding <=> query_embedding))::double precision as similarity
  from public.in_app_support_knowledge as knowledge
  where knowledge.is_active = true
    and (cardinality(knowledge.portals) = 0 or filter_portal = any(knowledge.portals))
    and (
      cardinality(knowledge.entity_types) = 0
      or (filter_entity_type is not null and filter_entity_type = any(knowledge.entity_types))
    )
    and (knowledge.organization_id is null or knowledge.organization_id = filter_organization_id)
    and (knowledge.feature_id is null or knowledge.feature_id = any(coalesce(filter_feature_ids, '{}'::text[])))
    and (
      knowledge.required_permission is null
      or knowledge.required_permission = any(coalesce(filter_permissions, '{}'::text[]))
    )
    and 1 - (knowledge.embedding <=> query_embedding) >= match_threshold
  order by knowledge.embedding <=> query_embedding
  limit least(greatest(match_count, 1), 8);
$$;

create or replace function public.match_in_app_support_memory(
  query_embedding extensions.vector(1536),
  match_threshold double precision,
  match_count integer,
  filter_user_id uuid,
  filter_conversation_id text,
  filter_organization_id uuid
)
returns table (
  id bigint,
  content text,
  similarity double precision
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  select
    memory.id,
    memory.content,
    (1 - (memory.embedding <=> query_embedding))::double precision as similarity
  from public.in_app_support_memory as memory
  where memory.user_id = filter_user_id
    and memory.conversation_id = filter_conversation_id
    and memory.organization_id is not distinct from filter_organization_id
    and memory.expires_at > now()
    and 1 - (memory.embedding <=> query_embedding) >= match_threshold
  order by memory.embedding <=> query_embedding
  limit least(greatest(match_count, 1), 8);
$$;

revoke all on function public.match_in_app_support_knowledge(
  extensions.vector, double precision, integer, text, text, uuid, text[], text[]
) from public, anon, authenticated;
revoke all on function public.match_in_app_support_memory(
  extensions.vector, double precision, integer, uuid, text, uuid
) from public, anon, authenticated;
grant execute on function public.match_in_app_support_knowledge(
  extensions.vector, double precision, integer, text, text, uuid, text[], text[]
) to service_role;
grant execute on function public.match_in_app_support_memory(
  extensions.vector, double precision, integer, uuid, text, uuid
) to service_role;
